//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSViewPagerPlugin\src\main\java\androidx\viewpager\widget\PagerTitleStrip.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_PagerTitleStrip")
#ifdef RESTRICT_PagerTitleStrip
#define INCLUDE_ALL_PagerTitleStrip 0
#else
#define INCLUDE_ALL_PagerTitleStrip 1
#endif
#undef RESTRICT_PagerTitleStrip

#if !defined (ASPagerTitleStrip_) && (INCLUDE_ALL_PagerTitleStrip || defined(INCLUDE_ASPagerTitleStrip))
#define ASPagerTitleStrip_

#define RESTRICT_ViewGroup 1
#define INCLUDE_ADViewGroup 1
#include "ViewGroup.h"

#define RESTRICT_ViewPager 1
#define INCLUDE_ASViewPager_IDecorView 1
#include "ViewPager.h"

@class ADTextView;
@class ASPagerAdapter;
@class ASViewPager;
@protocol ASHasWidgets;

@interface ASPagerTitleStrip : ADViewGroup < ASViewPager_IDecorView > {
 @public
  ASViewPager *mPager_;
  ADTextView *mPrevText_;
  ADTextView *mCurrText_;
  ADTextView *mNextText_;
  jfloat mLastKnownPositionOffset_;
  jint mTextColor_;
}

#pragma mark Public

- (instancetype)initWithASHasWidgets:(id<ASHasWidgets>)widget;

- (jint)getTextSpacing;

- (void)init__WithASHasWidgets:(id<ASHasWidgets>)widget OBJC_METHOD_FAMILY_NONE;

- (void)onAttachedToWindow;

- (void)onDetachedFromWindow;

- (void)requestLayout;

- (void)setGravityWithInt:(jint)gravity;

- (void)setNonPrimaryAlphaWithFloat:(jfloat)alpha;

- (void)setTextAppearanceWithId:(id)objValue;

- (void)setTextColorWithId:(id)objValue;

- (void)setTextSizeWithInt:(jint)unit
                 withFloat:(jfloat)size;

- (void)setTextSpacingWithInt:(jint)spacingPixels;

#pragma mark Protected

- (void)onLayoutWithBoolean:(jboolean)changed
                    withInt:(jint)l
                    withInt:(jint)t
                    withInt:(jint)r
                    withInt:(jint)b;

- (void)onMeasureWithInt:(jint)widthMeasureSpec
                 withInt:(jint)heightMeasureSpec;

#pragma mark Package-Private

- (jint)getMinHeight;

- (void)updateAdapterWithASPagerAdapter:(ASPagerAdapter *)oldAdapter
                     withASPagerAdapter:(ASPagerAdapter *)newAdapter;

- (void)updateTextWithInt:(jint)currentItem
       withASPagerAdapter:(ASPagerAdapter *)adapter;

- (void)updateTextPositionsWithInt:(jint)position
                         withFloat:(jfloat)positionOffset
                       withBoolean:(jboolean)force;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASPagerTitleStrip)

J2OBJC_FIELD_SETTER(ASPagerTitleStrip, mPager_, ASViewPager *)
J2OBJC_FIELD_SETTER(ASPagerTitleStrip, mPrevText_, ADTextView *)
J2OBJC_FIELD_SETTER(ASPagerTitleStrip, mCurrText_, ADTextView *)
J2OBJC_FIELD_SETTER(ASPagerTitleStrip, mNextText_, ADTextView *)

FOUNDATION_EXPORT void ASPagerTitleStrip_initWithASHasWidgets_(ASPagerTitleStrip *self, id<ASHasWidgets> widget);

FOUNDATION_EXPORT ASPagerTitleStrip *new_ASPagerTitleStrip_initWithASHasWidgets_(id<ASHasWidgets> widget) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASPagerTitleStrip *create_ASPagerTitleStrip_initWithASHasWidgets_(id<ASHasWidgets> widget);

J2OBJC_TYPE_LITERAL_HEADER(ASPagerTitleStrip)

@compatibility_alias AndroidxViewpagerWidgetPagerTitleStrip ASPagerTitleStrip;

#endif

#pragma pop_macro("INCLUDE_ALL_PagerTitleStrip")
