//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSViewPagerPlugin\src\main\java\androidx\viewpager\widget\PagerTabStrip.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_PagerTabStrip")
#ifdef RESTRICT_PagerTabStrip
#define INCLUDE_ALL_PagerTabStrip 0
#else
#define INCLUDE_ALL_PagerTabStrip 1
#endif
#undef RESTRICT_PagerTabStrip

#if !defined (ASPagerTabStrip_) && (INCLUDE_ALL_PagerTabStrip || defined(INCLUDE_ASPagerTabStrip))
#define ASPagerTabStrip_

#define RESTRICT_PagerTitleStrip 1
#define INCLUDE_ASPagerTitleStrip 1
#include "PagerTitleStrip.h"

@protocol ASHasWidgets;

@interface ASPagerTabStrip : ASPagerTitleStrip

#pragma mark Public

- (instancetype)initWithASHasWidgets:(id<ASHasWidgets>)widget;

- (void)init__WithASHasWidgets:(id<ASHasWidgets>)widget OBJC_METHOD_FAMILY_NONE;

- (void)setDrawFullUnderlineWithBoolean:(jboolean)drawFull;

- (void)setPaddingWithInt:(jint)left
                  withInt:(jint)top
                  withInt:(jint)right
                  withInt:(jint)bottom;

- (void)setTabIndicatorColorWithId:(id)objValue;

- (void)setTextSpacingWithInt:(jint)spacingPixels;

#pragma mark Package-Private

- (jint)getMinHeight;

- (void)updateTextPositionsWithInt:(jint)position
                         withFloat:(jfloat)positionOffset
                       withBoolean:(jboolean)force;

@end

J2OBJC_EMPTY_STATIC_INIT(ASPagerTabStrip)

FOUNDATION_EXPORT void ASPagerTabStrip_initWithASHasWidgets_(ASPagerTabStrip *self, id<ASHasWidgets> widget);

FOUNDATION_EXPORT ASPagerTabStrip *new_ASPagerTabStrip_initWithASHasWidgets_(id<ASHasWidgets> widget) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASPagerTabStrip *create_ASPagerTabStrip_initWithASHasWidgets_(id<ASHasWidgets> widget);

J2OBJC_TYPE_LITERAL_HEADER(ASPagerTabStrip)

@compatibility_alias AndroidxViewpagerWidgetPagerTabStrip ASPagerTabStrip;

#endif

#pragma pop_macro("INCLUDE_ALL_PagerTabStrip")
