//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSViewPagerPlugin\src\main\java\com\ashera\viewpager\PagerTitleStripImpl.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_PagerTitleStripImpl")
#ifdef RESTRICT_PagerTitleStripImpl
#define INCLUDE_ALL_PagerTitleStripImpl 0
#else
#define INCLUDE_ALL_PagerTitleStripImpl 1
#endif
#undef RESTRICT_PagerTitleStripImpl

#if !defined (ASPagerTitleStripImpl_) && (INCLUDE_ALL_PagerTitleStripImpl || defined(INCLUDE_ASPagerTitleStripImpl))
#define ASPagerTitleStripImpl_

#define RESTRICT_BaseHasWidgets 1
#define INCLUDE_ASBaseHasWidgets 1
#include "BaseHasWidgets.h"

@class ASWidgetAttribute;
@class IOSClass;
@protocol ASIFragment;
@protocol ASILifeCycleDecorator;
@protocol ASIWidget;
@protocol JavaUtilMap;

@interface ASPagerTitleStripImpl : ASBaseHasWidgets
@property id uiView;

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)localname;

- (instancetype)initWithNSString:(NSString *)groupName
                    withNSString:(NSString *)localname;

- (void)addWithASIWidget:(id<ASIWidget>)w
                 withInt:(jint)index;

- (id)asNativeWidget;

- (id)asWidget;

- (jboolean)checkIosVersionWithNSString:(NSString *)v;

- (void)createWithASIFragment:(id<ASIFragment>)fragment
              withJavaUtilMap:(id<JavaUtilMap>)params;

- (void)createPaneWithJavaUtilMap:(id<JavaUtilMap>)params;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
              withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (id)getChildAttributeWithASIWidget:(id<ASIWidget>)w
               withASWidgetAttribute:(ASWidgetAttribute *)key;

- (IOSClass *)getViewClass;

- (void)invalidate;

- (void)loadAttributesWithNSString:(NSString *)localName;

- (id<ASIWidget>)newInstance OBJC_METHOD_FAMILY_NONE;

- (jboolean)removeWithInt:(jint)index;

- (jboolean)removeWithASIWidget:(id<ASIWidget>)w;

- (void)requestLayout;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue
                withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (void)setChildAttributeWithASIWidget:(id<ASIWidget>)w
                 withASWidgetAttribute:(ASWidgetAttribute *)key
                          withNSString:(NSString *)strValue
                                withId:(id)objValue;

- (void)setIdWithNSString:(NSString *)id_;

- (void)setVisibleWithBoolean:(jboolean)b;

@end

J2OBJC_EMPTY_STATIC_INIT(ASPagerTitleStripImpl)

inline NSString *ASPagerTitleStripImpl_get_LOCAL_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASPagerTitleStripImpl_LOCAL_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASPagerTitleStripImpl, LOCAL_NAME, NSString *)

inline NSString *ASPagerTitleStripImpl_get_GROUP_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASPagerTitleStripImpl_GROUP_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASPagerTitleStripImpl, GROUP_NAME, NSString *)

FOUNDATION_EXPORT void ASPagerTitleStripImpl_init(ASPagerTitleStripImpl *self);

FOUNDATION_EXPORT ASPagerTitleStripImpl *new_ASPagerTitleStripImpl_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASPagerTitleStripImpl *create_ASPagerTitleStripImpl_init(void);

FOUNDATION_EXPORT void ASPagerTitleStripImpl_initWithNSString_(ASPagerTitleStripImpl *self, NSString *localname);

FOUNDATION_EXPORT ASPagerTitleStripImpl *new_ASPagerTitleStripImpl_initWithNSString_(NSString *localname) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASPagerTitleStripImpl *create_ASPagerTitleStripImpl_initWithNSString_(NSString *localname);

FOUNDATION_EXPORT void ASPagerTitleStripImpl_initWithNSString_withNSString_(ASPagerTitleStripImpl *self, NSString *groupName, NSString *localname);

FOUNDATION_EXPORT ASPagerTitleStripImpl *new_ASPagerTitleStripImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASPagerTitleStripImpl *create_ASPagerTitleStripImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname);

J2OBJC_TYPE_LITERAL_HEADER(ASPagerTitleStripImpl)

@compatibility_alias ComAsheraViewpagerPagerTitleStripImpl ASPagerTitleStripImpl;

#endif

#if !defined (ASPagerTitleStripImpl_PagerTitleStripExt_) && (INCLUDE_ALL_PagerTitleStripImpl || defined(INCLUDE_ASPagerTitleStripImpl_PagerTitleStripExt))
#define ASPagerTitleStripImpl_PagerTitleStripExt_

#define RESTRICT_PagerTitleStrip 1
#define INCLUDE_ADXPagerTitleStrip 1
#include "PagerTitleStrip.h"

#define RESTRICT_ILifeCycleDecorator 1
#define INCLUDE_ASILifeCycleDecorator 1
#include "ILifeCycleDecorator.h"

#define RESTRICT_IMaxDimension 1
#define INCLUDE_ASIMaxDimension 1
#include "IMaxDimension.h"

@class ADRect;
@class ADView;
@class ASPagerTitleStripImpl;
@class ASWidgetAttribute;
@class IOSIntArray;
@class IOSObjectArray;
@protocol ASHasWidgets;
@protocol ASIWidget;
@protocol JavaUtilList;

@interface ASPagerTitleStripImpl_PagerTitleStripExt : ADXPagerTitleStrip < ASILifeCycleDecorator, ASIMaxDimension >

#pragma mark Public

- (instancetype)initWithASPagerTitleStripImpl:(ASPagerTitleStripImpl *)outer$;

- (void)drawableStateChanged;

- (void)endViewTransitionWithADView:(ADView *)view;

- (void)executeWithNSString:(NSString *)method
          withNSObjectArray:(IOSObjectArray *)canvas;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute;

- (void)getLocationOnScreenWithIntArray:(IOSIntArray *)appScreenLocation;

- (jint)getMaxHeight;

- (jint)getMaxWidth;

- (id<JavaUtilList>)getMethods;

- (id<ASIWidget>)getWidget;

- (void)getWindowVisibleDisplayFrameWithADRect:(ADRect *)displayFrame;

- (ADView *)inflateViewWithNSString:(NSString *)layout;

- (void)initialized OBJC_METHOD_FAMILY_NONE;

- (id<ASILifeCycleDecorator>)newInstanceWithASIWidget:(id<ASIWidget>)widget OBJC_METHOD_FAMILY_NONE;

- (void)offsetLeftAndRightWithInt:(jint)offset;

- (void)offsetTopAndBottomWithInt:(jint)offset;

- (void)onMeasureWithInt:(jint)widthMeasureSpec
                 withInt:(jint)heightMeasureSpec;

- (void)remeasure;

- (void)removeFromParent;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue;

- (void)setMaxHeightWithInt:(jint)height;

- (void)setMaxWidthWithInt:(jint)width;

- (void)setMyAttributeWithNSString:(NSString *)name
                            withId:(id)value;

- (void)setState0WithId:(id)value;

- (void)setState1WithId:(id)value;

- (void)setState2WithId:(id)value;

- (void)setState3WithId:(id)value;

- (void)setState4WithId:(id)value;

- (void)setVisibilityWithInt:(jint)visibility;

- (void)state0;

- (void)state1;

- (void)state2;

- (void)state3;

- (void)state4;

- (void)stateNo;

- (void)stateYes;

- (void)updateMeasuredDimensionWithInt:(jint)width
                               withInt:(jint)height;

#pragma mark Protected

- (void)onLayoutWithBoolean:(jboolean)changed
                    withInt:(jint)l
                    withInt:(jint)t
                    withInt:(jint)r
                    withInt:(jint)b;

// Disallowed inherited constructors, do not use.

- (instancetype)initWithASHasWidgets:(id<ASHasWidgets>)arg0 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASPagerTitleStripImpl_PagerTitleStripExt)

FOUNDATION_EXPORT void ASPagerTitleStripImpl_PagerTitleStripExt_initWithASPagerTitleStripImpl_(ASPagerTitleStripImpl_PagerTitleStripExt *self, ASPagerTitleStripImpl *outer$);

FOUNDATION_EXPORT ASPagerTitleStripImpl_PagerTitleStripExt *new_ASPagerTitleStripImpl_PagerTitleStripExt_initWithASPagerTitleStripImpl_(ASPagerTitleStripImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASPagerTitleStripImpl_PagerTitleStripExt *create_ASPagerTitleStripImpl_PagerTitleStripExt_initWithASPagerTitleStripImpl_(ASPagerTitleStripImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASPagerTitleStripImpl_PagerTitleStripExt)

#endif

#pragma pop_macro("INCLUDE_ALL_PagerTitleStripImpl")
