//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSViewPagerPlugin\src\main\java\com\ashera\viewpager\PagerTabStripImpl.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_PagerTabStripImpl")
#ifdef RESTRICT_PagerTabStripImpl
#define INCLUDE_ALL_PagerTabStripImpl 0
#else
#define INCLUDE_ALL_PagerTabStripImpl 1
#endif
#undef RESTRICT_PagerTabStripImpl

#if !defined (ASPagerTabStripImpl_) && (INCLUDE_ALL_PagerTabStripImpl || defined(INCLUDE_ASPagerTabStripImpl))
#define ASPagerTabStripImpl_

#define RESTRICT_BaseHasWidgets 1
#define INCLUDE_ASBaseHasWidgets 1
#include "BaseHasWidgets.h"

@class ASWidgetAttribute;
@class IOSClass;
@protocol ASIFragment;
@protocol ASILifeCycleDecorator;
@protocol ASIWidget;
@protocol JavaUtilMap;

@interface ASPagerTabStripImpl : ASBaseHasWidgets
@property id uiView;

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)localname;

- (instancetype)initWithNSString:(NSString *)groupName
                    withNSString:(NSString *)localname;

- (void)addWithASIWidget:(id<ASIWidget>)w
                 withInt:(jint)index;

- (id)asNativeWidget;

- (id)asWidget;

- (jboolean)checkIosVersionWithNSString:(NSString *)v;

- (void)createWithASIFragment:(id<ASIFragment>)fragment
              withJavaUtilMap:(id<JavaUtilMap>)params;

- (void)createPaneWithJavaUtilMap:(id<JavaUtilMap>)params;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
              withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (id)getChildAttributeWithASIWidget:(id<ASIWidget>)w
               withASWidgetAttribute:(ASWidgetAttribute *)key;

- (IOSClass *)getViewClass;

- (void)invalidate;

- (void)loadAttributesWithNSString:(NSString *)localName;

- (id<ASIWidget>)newInstance OBJC_METHOD_FAMILY_NONE;

- (jboolean)removeWithInt:(jint)index;

- (jboolean)removeWithASIWidget:(id<ASIWidget>)w;

- (void)requestLayout;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue
                withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (void)setChildAttributeWithASIWidget:(id<ASIWidget>)w
                 withASWidgetAttribute:(ASWidgetAttribute *)key
                          withNSString:(NSString *)strValue
                                withId:(id)objValue;

- (void)setIdWithNSString:(NSString *)id_;

- (void)setVisibleWithBoolean:(jboolean)b;

@end

J2OBJC_EMPTY_STATIC_INIT(ASPagerTabStripImpl)

inline NSString *ASPagerTabStripImpl_get_LOCAL_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASPagerTabStripImpl_LOCAL_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASPagerTabStripImpl, LOCAL_NAME, NSString *)

inline NSString *ASPagerTabStripImpl_get_GROUP_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASPagerTabStripImpl_GROUP_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASPagerTabStripImpl, GROUP_NAME, NSString *)

FOUNDATION_EXPORT void ASPagerTabStripImpl_init(ASPagerTabStripImpl *self);

FOUNDATION_EXPORT ASPagerTabStripImpl *new_ASPagerTabStripImpl_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASPagerTabStripImpl *create_ASPagerTabStripImpl_init(void);

FOUNDATION_EXPORT void ASPagerTabStripImpl_initWithNSString_(ASPagerTabStripImpl *self, NSString *localname);

FOUNDATION_EXPORT ASPagerTabStripImpl *new_ASPagerTabStripImpl_initWithNSString_(NSString *localname) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASPagerTabStripImpl *create_ASPagerTabStripImpl_initWithNSString_(NSString *localname);

FOUNDATION_EXPORT void ASPagerTabStripImpl_initWithNSString_withNSString_(ASPagerTabStripImpl *self, NSString *groupName, NSString *localname);

FOUNDATION_EXPORT ASPagerTabStripImpl *new_ASPagerTabStripImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASPagerTabStripImpl *create_ASPagerTabStripImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname);

J2OBJC_TYPE_LITERAL_HEADER(ASPagerTabStripImpl)

@compatibility_alias ComAsheraViewpagerPagerTabStripImpl ASPagerTabStripImpl;

#endif

#if !defined (ASPagerTabStripImpl_PagerTabStripExt_) && (INCLUDE_ALL_PagerTabStripImpl || defined(INCLUDE_ASPagerTabStripImpl_PagerTabStripExt))
#define ASPagerTabStripImpl_PagerTabStripExt_

#define RESTRICT_PagerTabStrip 1
#define INCLUDE_ADXPagerTabStrip 1
#include "PagerTabStrip.h"

#define RESTRICT_ILifeCycleDecorator 1
#define INCLUDE_ASILifeCycleDecorator 1
#include "ILifeCycleDecorator.h"

#define RESTRICT_IMaxDimension 1
#define INCLUDE_ASIMaxDimension 1
#include "IMaxDimension.h"

@class ADRect;
@class ADView;
@class ASPagerTabStripImpl;
@class ASWidgetAttribute;
@class IOSIntArray;
@class IOSObjectArray;
@protocol ASHasWidgets;
@protocol ASIWidget;
@protocol JavaUtilList;

@interface ASPagerTabStripImpl_PagerTabStripExt : ADXPagerTabStrip < ASILifeCycleDecorator, ASIMaxDimension >

#pragma mark Public

- (instancetype)initWithASPagerTabStripImpl:(ASPagerTabStripImpl *)outer$;

- (void)drawableStateChanged;

- (void)endViewTransitionWithADView:(ADView *)view;

- (void)executeWithNSString:(NSString *)method
          withNSObjectArray:(IOSObjectArray *)canvas;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute;

- (void)getLocationOnScreenWithIntArray:(IOSIntArray *)appScreenLocation;

- (jint)getMaxHeight;

- (jint)getMaxWidth;

- (id<JavaUtilList>)getMethods;

- (id<ASIWidget>)getWidget;

- (void)getWindowVisibleDisplayFrameWithADRect:(ADRect *)displayFrame;

- (ADView *)inflateViewWithNSString:(NSString *)layout;

- (void)initialized OBJC_METHOD_FAMILY_NONE;

- (id<ASILifeCycleDecorator>)newInstanceWithASIWidget:(id<ASIWidget>)widget OBJC_METHOD_FAMILY_NONE;

- (void)offsetLeftAndRightWithInt:(jint)offset;

- (void)offsetTopAndBottomWithInt:(jint)offset;

- (void)onMeasureWithInt:(jint)widthMeasureSpec
                 withInt:(jint)heightMeasureSpec;

- (void)remeasure;

- (void)removeFromParent;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue;

- (void)setMaxHeightWithInt:(jint)height;

- (void)setMaxWidthWithInt:(jint)width;

- (void)setMyAttributeWithNSString:(NSString *)name
                            withId:(id)value;

- (void)setState0WithId:(id)value;

- (void)setState1WithId:(id)value;

- (void)setState2WithId:(id)value;

- (void)setState3WithId:(id)value;

- (void)setState4WithId:(id)value;

- (void)setVisibilityWithInt:(jint)visibility;

- (void)state0;

- (void)state1;

- (void)state2;

- (void)state3;

- (void)state4;

- (void)stateNo;

- (void)stateYes;

- (void)updateMeasuredDimensionWithInt:(jint)width
                               withInt:(jint)height;

#pragma mark Protected

- (void)onLayoutWithBoolean:(jboolean)changed
                    withInt:(jint)l
                    withInt:(jint)t
                    withInt:(jint)r
                    withInt:(jint)b;

// Disallowed inherited constructors, do not use.

- (instancetype)initWithASHasWidgets:(id<ASHasWidgets>)arg0 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASPagerTabStripImpl_PagerTabStripExt)

FOUNDATION_EXPORT void ASPagerTabStripImpl_PagerTabStripExt_initWithASPagerTabStripImpl_(ASPagerTabStripImpl_PagerTabStripExt *self, ASPagerTabStripImpl *outer$);

FOUNDATION_EXPORT ASPagerTabStripImpl_PagerTabStripExt *new_ASPagerTabStripImpl_PagerTabStripExt_initWithASPagerTabStripImpl_(ASPagerTabStripImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASPagerTabStripImpl_PagerTabStripExt *create_ASPagerTabStripImpl_PagerTabStripExt_initWithASPagerTabStripImpl_(ASPagerTabStripImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASPagerTabStripImpl_PagerTabStripExt)

#endif

#pragma pop_macro("INCLUDE_ALL_PagerTabStripImpl")
