//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSViewPagerPlugin\src\main\java\com\ashera\viewpager\PagerTabStripImpl.java
//

#include "BaseHasWidgets.h"
#include "HasWidgets.h"
#include "IAttributable.h"
#include "IFragment.h"
#include "ILifeCycleDecorator.h"
#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "IOSPrimitiveArray.h"
#include "IWidget.h"
#include "IWidgetLifeCycleListener.h"
#include "J2ObjC_source.h"
#include "LayoutTransition.h"
#include "MeasureEvent.h"
#include "OnLayoutEvent.h"
#include "PagerTabStrip.h"
#include "PagerTabStripImpl.h"
#include "Rect.h"
#include "View.h"
#include "ViewGroup.h"
#include "ViewGroupImpl.h"
#include "ViewImpl.h"
#include "WidgetAttribute.h"
#include "WidgetFactory.h"
#include "java/lang/Boolean.h"
#include "java/lang/Float.h"
#include "java/lang/Integer.h"
#include "java/lang/Runnable.h"
#include "java/lang/UnsupportedOperationException.h"
#include "java/util/HashMap.h"
#include "java/util/List.h"
#include "java/util/Map.h"

#include <UIKit/UIKit.h>
#include "ASUIView.h"
#include "HasLifeCycleDecorators.h"

@protocol JavaUtilMap;


#pragma clang diagnostic ignored "-Wprotocol"
#pragma clang diagnostic ignored "-Wincomplete-implementation"

@interface ASPagerTabStripImpl () {
 @public
  id uiView_;
  ASPagerTabStrip *pagerTabStrip_;
  ASPagerTabStripImpl_PagerTabStripCommandBuilder *builder_;
  ASPagerTabStripImpl_PagerTabStripBean *bean_;
  ASPagerTabStripImpl_PagerTabStripCommandParamsBuilder *paramsBuilder_;
  ASPagerTabStripImpl_PagerTabStripParamsBean *paramsBean_;
}

- (void)setWidgetOnNativeClass;

- (void)nativeRemoveViewWithASIWidget:(id<ASIWidget>)widget;

- (void)createLayoutParamsWithADView:(ADView *)view;

- (ADViewGroup_LayoutParams *)getLayoutParamsWithADView:(ADView *)view;

- (void)nativeCreateWithJavaUtilMap:(id<JavaUtilMap>)params;

- (void)setTextSizeWithId:(id)objValue;

- (void)setTextAppearanceWithId:(id)objValue;

@end

J2OBJC_FIELD_SETTER(ASPagerTabStripImpl, uiView_, id)
J2OBJC_FIELD_SETTER(ASPagerTabStripImpl, pagerTabStrip_, ASPagerTabStrip *)
J2OBJC_FIELD_SETTER(ASPagerTabStripImpl, builder_, ASPagerTabStripImpl_PagerTabStripCommandBuilder *)
J2OBJC_FIELD_SETTER(ASPagerTabStripImpl, bean_, ASPagerTabStripImpl_PagerTabStripBean *)
J2OBJC_FIELD_SETTER(ASPagerTabStripImpl, paramsBuilder_, ASPagerTabStripImpl_PagerTabStripCommandParamsBuilder *)
J2OBJC_FIELD_SETTER(ASPagerTabStripImpl, paramsBean_, ASPagerTabStripImpl_PagerTabStripParamsBean *)

__attribute__((unused)) static void ASPagerTabStripImpl_setWidgetOnNativeClass(ASPagerTabStripImpl *self);

__attribute__((unused)) static void ASPagerTabStripImpl_nativeRemoveViewWithASIWidget_(ASPagerTabStripImpl *self, id<ASIWidget> widget);

__attribute__((unused)) static void ASPagerTabStripImpl_createLayoutParamsWithADView_(ASPagerTabStripImpl *self, ADView *view);

__attribute__((unused)) static ADViewGroup_LayoutParams *ASPagerTabStripImpl_getLayoutParamsWithADView_(ASPagerTabStripImpl *self, ADView *view);

__attribute__((unused)) static void ASPagerTabStripImpl_nativeCreateWithJavaUtilMap_(ASPagerTabStripImpl *self, id<JavaUtilMap> params);

__attribute__((unused)) static void ASPagerTabStripImpl_setTextSizeWithId_(ASPagerTabStripImpl *self, id objValue);

__attribute__((unused)) static void ASPagerTabStripImpl_setTextAppearanceWithId_(ASPagerTabStripImpl *self, id objValue);

@interface ASPagerTabStripImpl_PagerTabStripExt () {
 @public
  __unsafe_unretained ASPagerTabStripImpl *this$0_;
  ASMeasureEvent *measureFinished_;
  ASOnLayoutEvent *onLayoutEvent_;
  jint mMaxWidth_;
  jint mMaxHeight_;
  id<JavaUtilMap> templates_;
}

@end

J2OBJC_FIELD_SETTER(ASPagerTabStripImpl_PagerTabStripExt, measureFinished_, ASMeasureEvent *)
J2OBJC_FIELD_SETTER(ASPagerTabStripImpl_PagerTabStripExt, onLayoutEvent_, ASOnLayoutEvent *)
J2OBJC_FIELD_SETTER(ASPagerTabStripImpl_PagerTabStripExt, templates_, id<JavaUtilMap>)

@interface ASPagerTabStripImpl_PagerTabStripCommandBuilder () {
 @public
  ASPagerTabStripImpl *this$0_;
}

@end

@interface ASPagerTabStripImpl_PagerTabStripBean () {
 @public
  ASPagerTabStripImpl *this$0_;
}

@end

@interface ASPagerTabStripImpl_$Lambda$1 : NSObject < JavaLangRunnable > {
 @public
  id<ASIWidget> val$widget_;
}

- (void)run;

@end

J2OBJC_EMPTY_STATIC_INIT(ASPagerTabStripImpl_$Lambda$1)

__attribute__((unused)) static void ASPagerTabStripImpl_$Lambda$1_initWithASIWidget_(ASPagerTabStripImpl_$Lambda$1 *self, id<ASIWidget> capture$0);

__attribute__((unused)) static ASPagerTabStripImpl_$Lambda$1 *new_ASPagerTabStripImpl_$Lambda$1_initWithASIWidget_(id<ASIWidget> capture$0) NS_RETURNS_RETAINED;

__attribute__((unused)) static ASPagerTabStripImpl_$Lambda$1 *create_ASPagerTabStripImpl_$Lambda$1_initWithASIWidget_(id<ASIWidget> capture$0);

NSString *ASPagerTabStripImpl_LOCAL_NAME = @"androidx.viewpager.widget.PagerTabStrip";
NSString *ASPagerTabStripImpl_GROUP_NAME = @"androidx.viewpager.widget.PagerTabStrip";

@implementation ASPagerTabStripImpl

@synthesize uiView = uiView_;

- (void)loadAttributesWithNSString:(NSString *)localName {
  ASViewGroupImpl_register__WithNSString_(localName);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName, [((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"textSpacing"])) withTypeWithNSString:@"dimension"]);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName, [((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"nonPrimaryAlpha"])) withTypeWithNSString:@"float"]);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName, [((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"textColor"])) withTypeWithNSString:@"color"]);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName, [((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"gravity"])) withTypeWithNSString:@"gravity"]);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName, [((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"textSize"])) withTypeWithNSString:@"dimensionsp"]);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName, [((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"textAppearance"])) withTypeWithNSString:@"style"]);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName, [((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"tabIndicatorColor"])) withTypeWithNSString:@"color"]);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName, [((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"drawFullUnderline"])) withTypeWithNSString:@"boolean"]);
}

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ASPagerTabStripImpl_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (instancetype)initWithNSString:(NSString *)localname {
  ASPagerTabStripImpl_initWithNSString_(self, localname);
  return self;
}

- (instancetype)initWithNSString:(NSString *)groupName
                    withNSString:(NSString *)localname {
  ASPagerTabStripImpl_initWithNSString_withNSString_(self, groupName, localname);
  return self;
}

- (id<ASIWidget>)newInstance {
  return new_ASPagerTabStripImpl_initWithNSString_withNSString_(groupName_, localName_);
}

- (void)createWithASIFragment:(id<ASIFragment>)fragment
              withJavaUtilMap:(id<JavaUtilMap>)params {
  [super createWithASIFragment:fragment withJavaUtilMap:params];
  pagerTabStrip_ = new_ASPagerTabStripImpl_PagerTabStripExt_initWithASPagerTabStripImpl_(self);
  ASPagerTabStripImpl_nativeCreateWithJavaUtilMap_(self, params);
  ASViewGroupImpl_registerCommandConveterWithASIWidget_(self);
  ASPagerTabStripImpl_setWidgetOnNativeClass(self);
}

- (void)setWidgetOnNativeClass {
  ASPagerTabStripImpl_setWidgetOnNativeClass(self);
}

- (id)asWidget {
  return pagerTabStrip_;
}

- (jboolean)removeWithASIWidget:(id<ASIWidget>)w {
  jboolean remove = [super removeWithASIWidget:w];
  [((ASPagerTabStrip *) nil_chk(pagerTabStrip_)) removeViewWithADView:(ADView *) cast_chk([((id<ASIWidget>) nil_chk(w)) asWidget], [ADView class])];
  ASPagerTabStripImpl_nativeRemoveViewWithASIWidget_(self, w);
  return remove;
}

- (jboolean)removeWithInt:(jint)index {
  id<ASIWidget> widget = [((id<JavaUtilList>) nil_chk(widgets_)) getWithInt:index];
  jboolean remove = [super removeWithInt:index];
  if (index + 1 <= [((ASPagerTabStrip *) nil_chk(pagerTabStrip_)) getChildCount]) {
    [((ASPagerTabStrip *) nil_chk(pagerTabStrip_)) removeViewAtWithInt:index];
    ASPagerTabStripImpl_nativeRemoveViewWithASIWidget_(self, widget);
  }
  return remove;
}

- (void)nativeRemoveViewWithASIWidget:(id<ASIWidget>)widget {
  ASPagerTabStripImpl_nativeRemoveViewWithASIWidget_(self, widget);
}

- (void)addWithASIWidget:(id<ASIWidget>)w
                 withInt:(jint)index {
  if (index != -2) {
    ADView *view = (ADView *) cast_chk([((id<ASIWidget>) nil_chk(w)) asWidget], [ADView class]);
    ASPagerTabStripImpl_createLayoutParamsWithADView_(self, view);
    if (index == -1) {
      [((ASPagerTabStrip *) nil_chk(pagerTabStrip_)) addViewWithADView:view];
    }
    else {
      [((ASPagerTabStrip *) nil_chk(pagerTabStrip_)) addViewWithADView:view withInt:index];
    }
  }
  ASViewGroupImpl_nativeAddViewWithId_withId_([self asNativeWidget], [((id<ASIWidget>) nil_chk(w)) asNativeWidget]);
  [super addWithASIWidget:w withInt:index];
}

- (void)createLayoutParamsWithADView:(ADView *)view {
  ASPagerTabStripImpl_createLayoutParamsWithADView_(self, view);
}

- (ADViewGroup_LayoutParams *)getLayoutParamsWithADView:(ADView *)view {
  return ASPagerTabStripImpl_getLayoutParamsWithADView_(self, view);
}

- (void)setChildAttributeWithASIWidget:(id<ASIWidget>)w
                 withASWidgetAttribute:(ASWidgetAttribute *)key
                          withNSString:(NSString *)strValue
                                withId:(id)objValue {
  ADView *view = (ADView *) cast_chk([((id<ASIWidget>) nil_chk(w)) asWidget], [ADView class]);
  ADViewGroup_LayoutParams *layoutParams = ASPagerTabStripImpl_getLayoutParamsWithADView_(self, view);
  ASViewGroupImpl_setChildAttributeWithASIWidget_withASWidgetAttribute_withId_withId_(w, key, objValue, layoutParams);
  switch (JreIndexOfStr([((ASWidgetAttribute *) nil_chk(key)) getAttributeName], (id[]){ @"layout_width", @"layout_height" }, 2)) {
    case 0:
    ((ADViewGroup_LayoutParams *) nil_chk(layoutParams))->width_ = [((JavaLangInteger *) nil_chk((JavaLangInteger *) cast_chk(objValue, [JavaLangInteger class]))) intValue];
    break;
    case 1:
    ((ADViewGroup_LayoutParams *) nil_chk(layoutParams))->height_ = [((JavaLangInteger *) nil_chk((JavaLangInteger *) cast_chk(objValue, [JavaLangInteger class]))) intValue];
    break;
    default:
    break;
  }
  [((ADView *) nil_chk(view)) setLayoutParamsWithADViewGroup_LayoutParams:layoutParams];
}

- (id)getChildAttributeWithASIWidget:(id<ASIWidget>)w
               withASWidgetAttribute:(ASWidgetAttribute *)key {
  id attributeValue = ASViewGroupImpl_getChildAttributeWithASIWidget_withASWidgetAttribute_(w, key);
  if (attributeValue != nil) {
    return attributeValue;
  }
  ADView *view = (ADView *) cast_chk([((id<ASIWidget>) nil_chk(w)) asWidget], [ADView class]);
  ADViewGroup_LayoutParams *layoutParams = ASPagerTabStripImpl_getLayoutParamsWithADView_(self, view);
  switch (JreIndexOfStr([((ASWidgetAttribute *) nil_chk(key)) getAttributeName], (id[]){ @"layout_width", @"layout_height" }, 2)) {
    case 0:
    return JavaLangInteger_valueOfWithInt_(((ADViewGroup_LayoutParams *) nil_chk(layoutParams))->width_);
    case 1:
    return JavaLangInteger_valueOfWithInt_(((ADViewGroup_LayoutParams *) nil_chk(layoutParams))->height_);
  }
  return nil;
}

- (IOSClass *)getViewClass {
  return ASPagerTabStripImpl_PagerTabStripExt_class_();
}

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue
                withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator {
  ASViewGroupImpl_setAttributeWithASIWidget_withASWidgetAttribute_withNSString_withId_withASILifeCycleDecorator_(self, key, strValue, objValue, decorator);
  id nativeWidget = [self asNativeWidget];
  switch (JreIndexOfStr([((ASWidgetAttribute *) nil_chk(key)) getAttributeName], (id[]){ @"textSpacing", @"nonPrimaryAlpha", @"textColor", @"gravity", @"textSize", @"textAppearance", @"tabIndicatorColor", @"drawFullUnderline" }, 8)) {
    case 0:
    {
      [((ASPagerTabStrip *) nil_chk(pagerTabStrip_)) setTextSpacingWithInt:[((JavaLangInteger *) nil_chk((JavaLangInteger *) cast_chk(objValue, [JavaLangInteger class]))) intValue]];
    }
    break;
    case 1:
    {
      [((ASPagerTabStrip *) nil_chk(pagerTabStrip_)) setNonPrimaryAlphaWithFloat:[((JavaLangFloat *) nil_chk((JavaLangFloat *) cast_chk(objValue, [JavaLangFloat class]))) floatValue]];
    }
    break;
    case 2:
    {
      [((ASPagerTabStrip *) nil_chk(pagerTabStrip_)) setTextColorWithId:objValue];
    }
    break;
    case 3:
    {
      [((ASPagerTabStrip *) nil_chk(pagerTabStrip_)) setGravityWithInt:[((JavaLangInteger *) nil_chk((JavaLangInteger *) cast_chk(objValue, [JavaLangInteger class]))) intValue]];
    }
    break;
    case 4:
    {
      ASPagerTabStripImpl_setTextSizeWithId_(self, objValue);
    }
    break;
    case 5:
    {
      ASPagerTabStripImpl_setTextAppearanceWithId_(self, objValue);
    }
    break;
    case 6:
    {
      [((ASPagerTabStrip *) nil_chk(pagerTabStrip_)) setTabIndicatorColorWithId:objValue];
    }
    break;
    case 7:
    {
      [((ASPagerTabStrip *) nil_chk(pagerTabStrip_)) setDrawFullUnderlineWithBoolean:[((JavaLangBoolean *) nil_chk((JavaLangBoolean *) cast_chk(objValue, [JavaLangBoolean class]))) booleanValue]];
    }
    break;
    default:
    break;
  }
}

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
              withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator {
  id attributeValue = ASViewGroupImpl_getAttributeWithASIWidget_withASWidgetAttribute_withASILifeCycleDecorator_(self, key, decorator);
  if (attributeValue != nil) {
    return attributeValue;
  }
  id nativeWidget = [self asNativeWidget];
  switch (JreIndexOfStr([((ASWidgetAttribute *) nil_chk(key)) getAttributeName], (id[]){  }, 0)) {
  }
  return nil;
}

- (id)asNativeWidget {
  return uiView_;
}

- (jboolean)checkIosVersionWithNSString:(NSString *)v {
  return ([[[UIDevice currentDevice] systemVersion] compare:v options:NSNumericSearch] == NSOrderedDescending);
}

- (void)requestLayout {
  if ([self isInitialised]) {
    ASViewImpl_requestLayoutWithASIWidget_withId_(self, [self asNativeWidget]);
  }
}

- (void)invalidate {
  if ([self isInitialised]) {
    ASViewImpl_invalidateWithASIWidget_withId_(self, [self asNativeWidget]);
  }
}

- (void)nativeCreateWithJavaUtilMap:(id<JavaUtilMap>)params {
  ASPagerTabStripImpl_nativeCreateWithJavaUtilMap_(self, params);
}

- (void)setTextSizeWithId:(id)objValue {
  ASPagerTabStripImpl_setTextSizeWithId_(self, objValue);
}

- (void)setTextAppearanceWithId:(id)objValue {
  ASPagerTabStripImpl_setTextAppearanceWithId_(self, objValue);
}

- (void)setIdWithNSString:(NSString *)id_ {
  if (id_ != nil && ![id_ isEqual:@""]) {
    [super setIdWithNSString:id_];
    [((ASPagerTabStrip *) nil_chk(pagerTabStrip_)) setIdWithInt:[((JavaLangInteger *) nil_chk((JavaLangInteger *) cast_chk([self quickConvertWithId:id_ withNSString:@"id"], [JavaLangInteger class]))) intValue]];
  }
}

- (void)setVisibleWithBoolean:(jboolean)b {
  [((ADView *) nil_chk(((ADView *) cast_chk([self asWidget], [ADView class])))) setVisibilityWithInt:b ? ADView_VISIBLE : ADView_GONE];
}

- (id)getPluginWithNSString:(NSString *)plugin {
  return [((id<ASIAttributable>) nil_chk(ASWidgetFactory_getAttributableWithNSString_(plugin))) newInstanceWithASIWidget:self];
}

- (ASPagerTabStripImpl_PagerTabStripBean *)getBean {
  if (bean_ == nil) {
    bean_ = new_ASPagerTabStripImpl_PagerTabStripBean_initWithASPagerTabStripImpl_(self);
  }
  return bean_;
}

- (ASPagerTabStripImpl_PagerTabStripCommandBuilder *)getBuilder {
  if (builder_ == nil) {
    builder_ = new_ASPagerTabStripImpl_PagerTabStripCommandBuilder_initWithASPagerTabStripImpl_(self);
  }
  return builder_;
}

- (ASPagerTabStripImpl_PagerTabStripParamsBean *)getParamsBean {
  if (paramsBean_ == nil) {
    paramsBean_ = new_ASPagerTabStripImpl_PagerTabStripParamsBean_initWithASPagerTabStripImpl_(self);
  }
  return paramsBean_;
}

- (ASPagerTabStripImpl_PagerTabStripCommandParamsBuilder *)getParamsBuilder {
  if (paramsBuilder_ == nil) {
    paramsBuilder_ = new_ASPagerTabStripImpl_PagerTabStripCommandParamsBuilder_initWithASPagerTabStripImpl_(self);
  }
  return paramsBuilder_;
}

- (void)createPaneWithJavaUtilMap:(id<JavaUtilMap>)params {
  ASUIView* uiView = [ASUIView new];
  uiView.backgroundColor = [UIColor clearColor];
  uiView_ = uiView;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "V", 0x1, 0, 1, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 1, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 2, -1, -1, -1, -1 },
    { NULL, "LASIWidget;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 3, 4, -1, 5, -1, -1 },
    { NULL, "V", 0x102, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "Z", 0x1, 6, 7, -1, -1, -1, -1 },
    { NULL, "Z", 0x1, 6, 8, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 9, 7, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 10, 11, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 12, 13, -1, -1, -1, -1 },
    { NULL, "LADViewGroup_LayoutParams;", 0x2, 14, 13, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 15, 16, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, 17, 18, -1, -1, -1, -1 },
    { NULL, "LIOSClass;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 19, 20, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, 21, 22, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "Z", 0x101, 23, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 24, 25, -1, 26, -1, -1 },
    { NULL, "V", 0x2, 27, 28, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 29, 28, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 30, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 31, 32, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, 33, 1, -1, -1, -1, -1 },
    { NULL, "LASPagerTabStripImpl_PagerTabStripBean;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LASPagerTabStripImpl_PagerTabStripCommandBuilder;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LASPagerTabStripImpl_PagerTabStripParamsBean;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LASPagerTabStripImpl_PagerTabStripCommandParamsBuilder;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x101, 34, 25, -1, 26, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(loadAttributesWithNSString:);
  methods[1].selector = @selector(init);
  methods[2].selector = @selector(initWithNSString:);
  methods[3].selector = @selector(initWithNSString:withNSString:);
  methods[4].selector = @selector(newInstance);
  methods[5].selector = @selector(createWithASIFragment:withJavaUtilMap:);
  methods[6].selector = @selector(setWidgetOnNativeClass);
  methods[7].selector = @selector(asWidget);
  methods[8].selector = @selector(removeWithASIWidget:);
  methods[9].selector = @selector(removeWithInt:);
  methods[10].selector = @selector(nativeRemoveViewWithASIWidget:);
  methods[11].selector = @selector(addWithASIWidget:withInt:);
  methods[12].selector = @selector(createLayoutParamsWithADView:);
  methods[13].selector = @selector(getLayoutParamsWithADView:);
  methods[14].selector = @selector(setChildAttributeWithASIWidget:withASWidgetAttribute:withNSString:withId:);
  methods[15].selector = @selector(getChildAttributeWithASIWidget:withASWidgetAttribute:);
  methods[16].selector = @selector(getViewClass);
  methods[17].selector = @selector(setAttributeWithASWidgetAttribute:withNSString:withId:withASILifeCycleDecorator:);
  methods[18].selector = @selector(getAttributeWithASWidgetAttribute:withASILifeCycleDecorator:);
  methods[19].selector = @selector(asNativeWidget);
  methods[20].selector = @selector(checkIosVersionWithNSString:);
  methods[21].selector = @selector(requestLayout);
  methods[22].selector = @selector(invalidate);
  methods[23].selector = @selector(nativeCreateWithJavaUtilMap:);
  methods[24].selector = @selector(setTextSizeWithId:);
  methods[25].selector = @selector(setTextAppearanceWithId:);
  methods[26].selector = @selector(setIdWithNSString:);
  methods[27].selector = @selector(setVisibleWithBoolean:);
  methods[28].selector = @selector(getPluginWithNSString:);
  methods[29].selector = @selector(getBean);
  methods[30].selector = @selector(getBuilder);
  methods[31].selector = @selector(getParamsBean);
  methods[32].selector = @selector(getParamsBuilder);
  methods[33].selector = @selector(createPaneWithJavaUtilMap:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "uiView_", "LNSObject;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "LOCAL_NAME", "LNSString;", .constantValue.asLong = 0, 0x19, -1, 35, -1, -1 },
    { "GROUP_NAME", "LNSString;", .constantValue.asLong = 0, 0x19, -1, 36, -1, -1 },
    { "pagerTabStrip_", "LASPagerTabStrip;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "builder_", "LASPagerTabStripImpl_PagerTabStripCommandBuilder;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "bean_", "LASPagerTabStripImpl_PagerTabStripBean;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "paramsBuilder_", "LASPagerTabStripImpl_PagerTabStripCommandParamsBuilder;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "paramsBean_", "LASPagerTabStripImpl_PagerTabStripParamsBean;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "loadAttributes", "LNSString;", "LNSString;LNSString;", "create", "LASIFragment;LJavaUtilMap;", "(Lcom/ashera/core/IFragment;Ljava/util/Map<Ljava/lang/String;Ljava/lang/Object;>;)V", "remove", "LASIWidget;", "I", "nativeRemoveView", "add", "LASIWidget;I", "createLayoutParams", "LADView;", "getLayoutParams", "setChildAttribute", "LASIWidget;LASWidgetAttribute;LNSString;LNSObject;", "getChildAttribute", "LASIWidget;LASWidgetAttribute;", "setAttribute", "LASWidgetAttribute;LNSString;LNSObject;LASILifeCycleDecorator;", "getAttribute", "LASWidgetAttribute;LASILifeCycleDecorator;", "checkIosVersion", "nativeCreate", "LJavaUtilMap;", "(Ljava/util/Map<Ljava/lang/String;Ljava/lang/Object;>;)V", "setTextSize", "LNSObject;", "setTextAppearance", "setId", "setVisible", "Z", "getPlugin", "createPane", &ASPagerTabStripImpl_LOCAL_NAME, &ASPagerTabStripImpl_GROUP_NAME, "LASPagerTabStripImpl_PagerTabStripExt;LASPagerTabStripImpl_PagerTabStripCommandBuilder;LASPagerTabStripImpl_PagerTabStripBean;LASPagerTabStripImpl_PagerTabStripParamsBean;LASPagerTabStripImpl_PagerTabStripCommandParamsBuilder;" };
  static const J2ObjcClassInfo _ASPagerTabStripImpl = { "PagerTabStripImpl", "com.ashera.viewpager", ptrTable, methods, fields, 7, 0x1, 34, 8, -1, 37, -1, -1, -1 };
  return &_ASPagerTabStripImpl;
}

@end

void ASPagerTabStripImpl_init(ASPagerTabStripImpl *self) {
  ASBaseHasWidgets_initWithNSString_withNSString_(self, ASPagerTabStripImpl_GROUP_NAME, ASPagerTabStripImpl_LOCAL_NAME);
}

ASPagerTabStripImpl *new_ASPagerTabStripImpl_init() {
  J2OBJC_NEW_IMPL(ASPagerTabStripImpl, init)
}

ASPagerTabStripImpl *create_ASPagerTabStripImpl_init() {
  J2OBJC_CREATE_IMPL(ASPagerTabStripImpl, init)
}

void ASPagerTabStripImpl_initWithNSString_(ASPagerTabStripImpl *self, NSString *localname) {
  ASBaseHasWidgets_initWithNSString_withNSString_(self, ASPagerTabStripImpl_GROUP_NAME, localname);
}

ASPagerTabStripImpl *new_ASPagerTabStripImpl_initWithNSString_(NSString *localname) {
  J2OBJC_NEW_IMPL(ASPagerTabStripImpl, initWithNSString_, localname)
}

ASPagerTabStripImpl *create_ASPagerTabStripImpl_initWithNSString_(NSString *localname) {
  J2OBJC_CREATE_IMPL(ASPagerTabStripImpl, initWithNSString_, localname)
}

void ASPagerTabStripImpl_initWithNSString_withNSString_(ASPagerTabStripImpl *self, NSString *groupName, NSString *localname) {
  ASBaseHasWidgets_initWithNSString_withNSString_(self, groupName, localname);
}

ASPagerTabStripImpl *new_ASPagerTabStripImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname) {
  J2OBJC_NEW_IMPL(ASPagerTabStripImpl, initWithNSString_withNSString_, groupName, localname)
}

ASPagerTabStripImpl *create_ASPagerTabStripImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname) {
  J2OBJC_CREATE_IMPL(ASPagerTabStripImpl, initWithNSString_withNSString_, groupName, localname)
}

void ASPagerTabStripImpl_setWidgetOnNativeClass(ASPagerTabStripImpl *self) {
  ((ASUIView*) [self asNativeWidget]).widget = self;
}

void ASPagerTabStripImpl_nativeRemoveViewWithASIWidget_(ASPagerTabStripImpl *self, id<ASIWidget> widget) {
  ADLayoutTransition *layoutTransition = [((ASPagerTabStrip *) nil_chk(self->pagerTabStrip_)) getLayoutTransition];
  if (layoutTransition != nil && ([layoutTransition isTransitionTypeEnabledWithInt:ADLayoutTransition_CHANGE_DISAPPEARING] || [layoutTransition isTransitionTypeEnabledWithInt:ADLayoutTransition_DISAPPEARING])) {
    [self addToBufferedRunnablesWithJavaLangRunnable:new_ASPagerTabStripImpl_$Lambda$1_initWithASIWidget_(widget)];
  }
  else {
    ASViewGroupImpl_nativeRemoveViewWithASIWidget_(widget);
  }
}

void ASPagerTabStripImpl_createLayoutParamsWithADView_(ASPagerTabStripImpl *self, ADView *view) {
  ADViewGroup_LayoutParams *layoutParams = [((ADView *) nil_chk(view)) getLayoutParams];
  layoutParams = [view getLayoutParams];
  if (layoutParams == nil) {
    layoutParams = new_ADViewGroup_LayoutParams_initWithInt_withInt_(-2, -2);
    [view setLayoutParamsWithADViewGroup_LayoutParams:layoutParams];
  }
  else {
    layoutParams->height_ = -2;
    layoutParams->width_ = -2;
  }
}

ADViewGroup_LayoutParams *ASPagerTabStripImpl_getLayoutParamsWithADView_(ASPagerTabStripImpl *self, ADView *view) {
  return [((ADView *) nil_chk(view)) getLayoutParams];
}

void ASPagerTabStripImpl_nativeCreateWithJavaUtilMap_(ASPagerTabStripImpl *self, id<JavaUtilMap> params) {
  [self createPaneWithJavaUtilMap:params];
  [((ASPagerTabStrip *) nil_chk(self->pagerTabStrip_)) init__WithASHasWidgets:self];
}

void ASPagerTabStripImpl_setTextSizeWithId_(ASPagerTabStripImpl *self, id objValue) {
  [((ASPagerTabStrip *) nil_chk(self->pagerTabStrip_)) setTextSizeWithInt:0 withFloat:[((JavaLangFloat *) nil_chk((JavaLangFloat *) cast_chk(objValue, [JavaLangFloat class]))) floatValue]];
}

void ASPagerTabStripImpl_setTextAppearanceWithId_(ASPagerTabStripImpl *self, id objValue) {
  [((ASPagerTabStrip *) nil_chk(self->pagerTabStrip_)) setTextAppearanceWithId:objValue];
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ASPagerTabStripImpl)

@implementation ASPagerTabStripImpl_PagerTabStripExt

- (id<ASIWidget>)getWidget {
  return this$0_;
}

- (void)setMaxWidthWithInt:(jint)width {
  mMaxWidth_ = width;
}

- (void)setMaxHeightWithInt:(jint)height {
  mMaxHeight_ = height;
}

- (jint)getMaxWidth {
  return mMaxWidth_;
}

- (jint)getMaxHeight {
  return mMaxHeight_;
}

- (instancetype)initWithASPagerTabStripImpl:(ASPagerTabStripImpl *)outer$ {
  ASPagerTabStripImpl_PagerTabStripExt_initWithASPagerTabStripImpl_(self, outer$);
  return self;
}

- (void)onMeasureWithInt:(jint)widthMeasureSpec
                 withInt:(jint)heightMeasureSpec {
  if (mMaxWidth_ > 0) {
    widthMeasureSpec = ADView_MeasureSpec_makeMeasureSpecWithInt_withInt_(mMaxWidth_, ADView_MeasureSpec_AT_MOST);
  }
  if (mMaxHeight_ > 0) {
    heightMeasureSpec = ADView_MeasureSpec_makeMeasureSpecWithInt_withInt_(mMaxHeight_, ADView_MeasureSpec_AT_MOST);
  }
  [super onMeasureWithInt:widthMeasureSpec withInt:heightMeasureSpec];
  id<ASIWidgetLifeCycleListener> listener = [this$0_ getListener];
  if (listener != nil) {
    [((ASMeasureEvent *) nil_chk(measureFinished_)) setWidthWithInt:[self getMeasuredWidth]];
    [((ASMeasureEvent *) nil_chk(measureFinished_)) setHeightWithInt:[self getMeasuredHeight]];
    [listener eventOccurredWithASIWidgetLifeCycleListener_EventId:JreLoadEnum(ASIWidgetLifeCycleListener_EventId, measureFinished) withASWidgetEvent:measureFinished_];
  }
}

- (void)onLayoutWithBoolean:(jboolean)changed
                    withInt:(jint)l
                    withInt:(jint)t
                    withInt:(jint)r
                    withInt:(jint)b {
  [super onLayoutWithBoolean:changed withInt:l withInt:t withInt:r withInt:b];
  ASViewImpl_setDrawableBoundsWithASIWidget_withInt_withInt_withInt_withInt_(this$0_, l, t, r, b);
  ASViewImpl_nativeMakeFrameWithId_withInt_withInt_withInt_withInt_([this$0_ asNativeWidget], l, t, r, b);
  [this$0_ replayBufferedEvents];
  ASViewImpl_redrawDrawablesWithASIWidget_(this$0_);
  id<ASIWidgetLifeCycleListener> listener = [this$0_ getListener];
  if (listener != nil) {
    [((ASOnLayoutEvent *) nil_chk(onLayoutEvent_)) setBWithInt:b];
    [((ASOnLayoutEvent *) nil_chk(onLayoutEvent_)) setLWithInt:l];
    [((ASOnLayoutEvent *) nil_chk(onLayoutEvent_)) setRWithInt:r];
    [((ASOnLayoutEvent *) nil_chk(onLayoutEvent_)) setTWithInt:t];
    [((ASOnLayoutEvent *) nil_chk(onLayoutEvent_)) setChangedWithBoolean:changed];
    [listener eventOccurredWithASIWidgetLifeCycleListener_EventId:JreLoadEnum(ASIWidgetLifeCycleListener_EventId, onLayout) withASWidgetEvent:onLayoutEvent_];
  }
  if ([this$0_ isInvalidateOnFrameChange] && [this$0_ isInitialised]) {
    [this$0_ invalidate];
  }
}

- (void)executeWithNSString:(NSString *)method
          withNSObjectArray:(IOSObjectArray *)canvas {
}

- (void)updateMeasuredDimensionWithInt:(jint)width
                               withInt:(jint)height {
  [self setMeasuredDimensionWithInt:width withInt:height];
}

- (id<ASILifeCycleDecorator>)newInstanceWithASIWidget:(id<ASIWidget>)widget {
  @throw new_JavaLangUnsupportedOperationException_init();
}

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue {
  @throw new_JavaLangUnsupportedOperationException_init();
}

- (id<JavaUtilList>)getMethods {
  @throw new_JavaLangUnsupportedOperationException_init();
}

- (void)initialized {
  @throw new_JavaLangUnsupportedOperationException_init();
}

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute {
  @throw new_JavaLangUnsupportedOperationException_init();
}

- (void)drawableStateChanged {
  [super drawableStateChanged];
  ASViewImpl_drawableStateChangedWithASIWidget_(this$0_);
}

- (ADView *)inflateViewWithNSString:(NSString *)layout {
  if (templates_ == nil) {
    templates_ = new_JavaUtilHashMap_init();
  }
  id<ASIWidget> template_ = [templates_ getWithId:layout];
  if (template_ == nil) {
    template_ = (id<ASIWidget>) cast_check([this$0_ quickConvertWithId:layout withNSString:@"template"], ASIWidget_class_());
    (void) [((id<JavaUtilMap>) nil_chk(templates_)) putWithId:layout withId:template_];
  }
  id<ASIWidget> widget = [((id<ASIWidget>) nil_chk(template_)) loadLazyWidgetsWithASHasWidgets:[this$0_ getParent]];
  return (ADView *) cast_chk([((id<ASIWidget>) nil_chk(widget)) asWidget], [ADView class]);
}

- (void)remeasure {
  if ([this$0_ getFragment] != nil) {
    [((id<ASIFragment>) nil_chk([this$0_ getFragment])) remeasure];
  }
}

- (void)removeFromParent {
  [((id<ASHasWidgets>) nil_chk([this$0_ getParent])) removeWithASIWidget:this$0_];
}

- (void)getLocationOnScreenWithIntArray:(IOSIntArray *)appScreenLocation {
  *IOSIntArray_GetRef(nil_chk(appScreenLocation), 0) = ASViewImpl_getLocationXOnScreenWithId_([this$0_ asNativeWidget]);
  *IOSIntArray_GetRef(appScreenLocation, 1) = ASViewImpl_getLocationYOnScreenWithId_([this$0_ asNativeWidget]);
}

- (void)getWindowVisibleDisplayFrameWithADRect:(ADRect *)displayFrame {
  ((ADRect *) nil_chk(displayFrame))->left_ = ASViewImpl_getLocationXOnScreenWithId_([this$0_ asNativeWidget]);
  displayFrame->top_ = ASViewImpl_getLocationYOnScreenWithId_([this$0_ asNativeWidget]);
  displayFrame->right_ = displayFrame->left_ + [self getWidth];
  displayFrame->bottom_ = displayFrame->top_ + [self getHeight];
}

- (void)offsetTopAndBottomWithInt:(jint)offset {
  [super offsetTopAndBottomWithInt:offset];
  ASViewImpl_nativeMakeFrameWithId_withInt_withInt_withInt_withInt_([this$0_ asNativeWidget], [self getLeft], [self getTop], [self getRight], [self getBottom]);
}

- (void)offsetLeftAndRightWithInt:(jint)offset {
  [super offsetLeftAndRightWithInt:offset];
  ASViewImpl_nativeMakeFrameWithId_withInt_withInt_withInt_withInt_([this$0_ asNativeWidget], [self getLeft], [self getTop], [self getRight], [self getBottom]);
}

- (void)setMyAttributeWithNSString:(NSString *)name
                            withId:(id)value {
  if ([((NSString *) nil_chk(name)) isEqual:@"state0"]) {
    [self setState0WithId:value];
    return;
  }
  if ([name isEqual:@"state1"]) {
    [self setState1WithId:value];
    return;
  }
  if ([name isEqual:@"state2"]) {
    [self setState2WithId:value];
    return;
  }
  if ([name isEqual:@"state3"]) {
    [self setState3WithId:value];
    return;
  }
  if ([name isEqual:@"state4"]) {
    [self setState4WithId:value];
    return;
  }
  [this$0_ setAttributeWithNSString:name withId:value withBoolean:true];
}

- (void)setVisibilityWithInt:(jint)visibility {
  [super setVisibilityWithInt:visibility];
  ASViewImpl_nativeSetVisibilityWithId_withBoolean_([this$0_ asNativeWidget], visibility != ADView_VISIBLE);
}

- (void)setState0WithId:(id)value {
  ASViewImpl_setStateWithASIWidget_withInt_withId_(this$0_, 0, value);
}

- (void)setState1WithId:(id)value {
  ASViewImpl_setStateWithASIWidget_withInt_withId_(this$0_, 1, value);
}

- (void)setState2WithId:(id)value {
  ASViewImpl_setStateWithASIWidget_withInt_withId_(this$0_, 2, value);
}

- (void)setState3WithId:(id)value {
  ASViewImpl_setStateWithASIWidget_withInt_withId_(this$0_, 3, value);
}

- (void)setState4WithId:(id)value {
  ASViewImpl_setStateWithASIWidget_withInt_withId_(this$0_, 4, value);
}

- (void)state0 {
  ASViewImpl_stateWithASIWidget_withInt_(this$0_, 0);
}

- (void)state1 {
  ASViewImpl_stateWithASIWidget_withInt_(this$0_, 1);
}

- (void)state2 {
  ASViewImpl_stateWithASIWidget_withInt_(this$0_, 2);
}

- (void)state3 {
  ASViewImpl_stateWithASIWidget_withInt_(this$0_, 3);
}

- (void)state4 {
  ASViewImpl_stateWithASIWidget_withInt_(this$0_, 4);
}

- (void)stateYes {
  ASViewImpl_stateYesWithASIWidget_(this$0_);
}

- (void)stateNo {
  ASViewImpl_stateNoWithASIWidget_(this$0_);
}

- (void)endViewTransitionWithADView:(ADView *)view {
  [super endViewTransitionWithADView:view];
  [this$0_ runBufferedRunnables];
}

- (void)__javaClone:(ASPagerTabStripImpl_PagerTabStripExt *)original {
  [super __javaClone:original];
  JreRelease(this$0_);
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "LASIWidget;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 0, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 2, 1, -1, -1, -1, -1 },
    { NULL, "I", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "I", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 3, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 4, 5, -1, -1, -1, -1 },
    { NULL, "V", 0x4, 6, 7, -1, -1, -1, -1 },
    { NULL, "V", 0x81, 8, 9, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 10, 5, -1, -1, -1, -1 },
    { NULL, "LASILifeCycleDecorator;", 0x1, 11, 12, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 13, 14, -1, -1, -1, -1 },
    { NULL, "LJavaUtilList;", 0x1, -1, -1, -1, 15, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, 16, 17, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LADView;", 0x1, 18, 19, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 20, 21, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 22, 23, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 24, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 25, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 26, 27, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 28, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 29, 30, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 31, 30, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 32, 30, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 33, 30, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 34, 30, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 35, 36, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(getWidget);
  methods[1].selector = @selector(setMaxWidthWithInt:);
  methods[2].selector = @selector(setMaxHeightWithInt:);
  methods[3].selector = @selector(getMaxWidth);
  methods[4].selector = @selector(getMaxHeight);
  methods[5].selector = @selector(initWithASPagerTabStripImpl:);
  methods[6].selector = @selector(onMeasureWithInt:withInt:);
  methods[7].selector = @selector(onLayoutWithBoolean:withInt:withInt:withInt:withInt:);
  methods[8].selector = @selector(executeWithNSString:withNSObjectArray:);
  methods[9].selector = @selector(updateMeasuredDimensionWithInt:withInt:);
  methods[10].selector = @selector(newInstanceWithASIWidget:);
  methods[11].selector = @selector(setAttributeWithASWidgetAttribute:withNSString:withId:);
  methods[12].selector = @selector(getMethods);
  methods[13].selector = @selector(initialized);
  methods[14].selector = @selector(getAttributeWithASWidgetAttribute:);
  methods[15].selector = @selector(drawableStateChanged);
  methods[16].selector = @selector(inflateViewWithNSString:);
  methods[17].selector = @selector(remeasure);
  methods[18].selector = @selector(removeFromParent);
  methods[19].selector = @selector(getLocationOnScreenWithIntArray:);
  methods[20].selector = @selector(getWindowVisibleDisplayFrameWithADRect:);
  methods[21].selector = @selector(offsetTopAndBottomWithInt:);
  methods[22].selector = @selector(offsetLeftAndRightWithInt:);
  methods[23].selector = @selector(setMyAttributeWithNSString:withId:);
  methods[24].selector = @selector(setVisibilityWithInt:);
  methods[25].selector = @selector(setState0WithId:);
  methods[26].selector = @selector(setState1WithId:);
  methods[27].selector = @selector(setState2WithId:);
  methods[28].selector = @selector(setState3WithId:);
  methods[29].selector = @selector(setState4WithId:);
  methods[30].selector = @selector(state0);
  methods[31].selector = @selector(state1);
  methods[32].selector = @selector(state2);
  methods[33].selector = @selector(state3);
  methods[34].selector = @selector(state4);
  methods[35].selector = @selector(stateYes);
  methods[36].selector = @selector(stateNo);
  methods[37].selector = @selector(endViewTransitionWithADView:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "this$0_", "LASPagerTabStripImpl;", .constantValue.asLong = 0, 0x1012, -1, -1, -1, -1 },
    { "measureFinished_", "LASMeasureEvent;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "onLayoutEvent_", "LASOnLayoutEvent;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "mMaxWidth_", "I", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "mMaxHeight_", "I", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "templates_", "LJavaUtilMap;", .constantValue.asLong = 0, 0x2, -1, -1, 37, -1 },
  };
  static const void *ptrTable[] = { "setMaxWidth", "I", "setMaxHeight", "LASPagerTabStripImpl;", "onMeasure", "II", "onLayout", "ZIIII", "execute", "LNSString;[LNSObject;", "updateMeasuredDimension", "newInstance", "LASIWidget;", "setAttribute", "LASWidgetAttribute;LNSString;LNSObject;", "()Ljava/util/List<Ljava/lang/String;>;", "getAttribute", "LASWidgetAttribute;", "inflateView", "LNSString;", "getLocationOnScreen", "[I", "getWindowVisibleDisplayFrame", "LADRect;", "offsetTopAndBottom", "offsetLeftAndRight", "setMyAttribute", "LNSString;LNSObject;", "setVisibility", "setState0", "LNSObject;", "setState1", "setState2", "setState3", "setState4", "endViewTransition", "LADView;", "Ljava/util/Map<Ljava/lang/String;Lcom/ashera/widget/IWidget;>;" };
  static const J2ObjcClassInfo _ASPagerTabStripImpl_PagerTabStripExt = { "PagerTabStripExt", "com.ashera.viewpager", ptrTable, methods, fields, 7, 0x1, 38, 6, 3, -1, -1, -1, -1 };
  return &_ASPagerTabStripImpl_PagerTabStripExt;
}

@end

void ASPagerTabStripImpl_PagerTabStripExt_initWithASPagerTabStripImpl_(ASPagerTabStripImpl_PagerTabStripExt *self, ASPagerTabStripImpl *outer$) {
  self->this$0_ = outer$;
  ASPagerTabStrip_initWithASHasWidgets_(self, outer$);
  self->measureFinished_ = new_ASMeasureEvent_init();
  self->onLayoutEvent_ = new_ASOnLayoutEvent_init();
  self->mMaxWidth_ = -1;
  self->mMaxHeight_ = -1;
}

ASPagerTabStripImpl_PagerTabStripExt *new_ASPagerTabStripImpl_PagerTabStripExt_initWithASPagerTabStripImpl_(ASPagerTabStripImpl *outer$) {
  J2OBJC_NEW_IMPL(ASPagerTabStripImpl_PagerTabStripExt, initWithASPagerTabStripImpl_, outer$)
}

ASPagerTabStripImpl_PagerTabStripExt *create_ASPagerTabStripImpl_PagerTabStripExt_initWithASPagerTabStripImpl_(ASPagerTabStripImpl *outer$) {
  J2OBJC_CREATE_IMPL(ASPagerTabStripImpl_PagerTabStripExt, initWithASPagerTabStripImpl_, outer$)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ASPagerTabStripImpl_PagerTabStripExt)

@implementation ASPagerTabStripImpl_PagerTabStripCommandBuilder

- (instancetype)initWithASPagerTabStripImpl:(ASPagerTabStripImpl *)outer$ {
  ASPagerTabStripImpl_PagerTabStripCommandBuilder_initWithASPagerTabStripImpl_(self, outer$);
  return self;
}

- (ASPagerTabStripImpl_PagerTabStripCommandBuilder *)executeWithBoolean:(jboolean)setter {
  if (setter) {
    [this$0_ executeCommandWithJavaUtilMap:command_ withASIWidget_CommandCallBack:nil withInt:ASIWidget_COMMAND_EXEC_SETTER_METHOD];
    [((id<ASIFragment>) nil_chk([this$0_ getFragment])) remeasure];
  }
  [this$0_ executeCommandWithJavaUtilMap:command_ withASIWidget_CommandCallBack:nil withInt:ASIWidget_COMMAND_EXEC_GETTER_METHOD];
  return self;
}

- (ASPagerTabStripImpl_PagerTabStripCommandBuilder *)setTextSpacingWithNSString:(NSString *)value {
  id<JavaUtilMap> attrs = [self initCommandWithNSString:@"textSpacing"];
  (void) [((id<JavaUtilMap>) nil_chk(attrs)) putWithId:@"type" withId:@"attribute"];
  (void) [attrs putWithId:@"setter" withId:JavaLangBoolean_valueOfWithBoolean_(true)];
  (void) [attrs putWithId:@"orderSet" withId:JavaLangInteger_valueOfWithInt_(++orderSet_)];
  (void) [attrs putWithId:@"value" withId:value];
  return self;
}

- (ASPagerTabStripImpl_PagerTabStripCommandBuilder *)setNonPrimaryAlphaWithFloat:(jfloat)value {
  id<JavaUtilMap> attrs = [self initCommandWithNSString:@"nonPrimaryAlpha"];
  (void) [((id<JavaUtilMap>) nil_chk(attrs)) putWithId:@"type" withId:@"attribute"];
  (void) [attrs putWithId:@"setter" withId:JavaLangBoolean_valueOfWithBoolean_(true)];
  (void) [attrs putWithId:@"orderSet" withId:JavaLangInteger_valueOfWithInt_(++orderSet_)];
  (void) [attrs putWithId:@"value" withId:JavaLangFloat_valueOfWithFloat_(value)];
  return self;
}

- (ASPagerTabStripImpl_PagerTabStripCommandBuilder *)setTextColorWithNSString:(NSString *)value {
  id<JavaUtilMap> attrs = [self initCommandWithNSString:@"textColor"];
  (void) [((id<JavaUtilMap>) nil_chk(attrs)) putWithId:@"type" withId:@"attribute"];
  (void) [attrs putWithId:@"setter" withId:JavaLangBoolean_valueOfWithBoolean_(true)];
  (void) [attrs putWithId:@"orderSet" withId:JavaLangInteger_valueOfWithInt_(++orderSet_)];
  (void) [attrs putWithId:@"value" withId:value];
  return self;
}

- (ASPagerTabStripImpl_PagerTabStripCommandBuilder *)setGravityWithNSString:(NSString *)value {
  id<JavaUtilMap> attrs = [self initCommandWithNSString:@"gravity"];
  (void) [((id<JavaUtilMap>) nil_chk(attrs)) putWithId:@"type" withId:@"attribute"];
  (void) [attrs putWithId:@"setter" withId:JavaLangBoolean_valueOfWithBoolean_(true)];
  (void) [attrs putWithId:@"orderSet" withId:JavaLangInteger_valueOfWithInt_(++orderSet_)];
  (void) [attrs putWithId:@"value" withId:value];
  return self;
}

- (ASPagerTabStripImpl_PagerTabStripCommandBuilder *)setTextSizeWithNSString:(NSString *)value {
  id<JavaUtilMap> attrs = [self initCommandWithNSString:@"textSize"];
  (void) [((id<JavaUtilMap>) nil_chk(attrs)) putWithId:@"type" withId:@"attribute"];
  (void) [attrs putWithId:@"setter" withId:JavaLangBoolean_valueOfWithBoolean_(true)];
  (void) [attrs putWithId:@"orderSet" withId:JavaLangInteger_valueOfWithInt_(++orderSet_)];
  (void) [attrs putWithId:@"value" withId:value];
  return self;
}

- (ASPagerTabStripImpl_PagerTabStripCommandBuilder *)setTextAppearanceWithNSString:(NSString *)value {
  id<JavaUtilMap> attrs = [self initCommandWithNSString:@"textAppearance"];
  (void) [((id<JavaUtilMap>) nil_chk(attrs)) putWithId:@"type" withId:@"attribute"];
  (void) [attrs putWithId:@"setter" withId:JavaLangBoolean_valueOfWithBoolean_(true)];
  (void) [attrs putWithId:@"orderSet" withId:JavaLangInteger_valueOfWithInt_(++orderSet_)];
  (void) [attrs putWithId:@"value" withId:value];
  return self;
}

- (ASPagerTabStripImpl_PagerTabStripCommandBuilder *)setTabIndicatorColorWithNSString:(NSString *)value {
  id<JavaUtilMap> attrs = [self initCommandWithNSString:@"tabIndicatorColor"];
  (void) [((id<JavaUtilMap>) nil_chk(attrs)) putWithId:@"type" withId:@"attribute"];
  (void) [attrs putWithId:@"setter" withId:JavaLangBoolean_valueOfWithBoolean_(true)];
  (void) [attrs putWithId:@"orderSet" withId:JavaLangInteger_valueOfWithInt_(++orderSet_)];
  (void) [attrs putWithId:@"value" withId:value];
  return self;
}

- (ASPagerTabStripImpl_PagerTabStripCommandBuilder *)setDrawFullUnderlineWithBoolean:(jboolean)value {
  id<JavaUtilMap> attrs = [self initCommandWithNSString:@"drawFullUnderline"];
  (void) [((id<JavaUtilMap>) nil_chk(attrs)) putWithId:@"type" withId:@"attribute"];
  (void) [attrs putWithId:@"setter" withId:JavaLangBoolean_valueOfWithBoolean_(true)];
  (void) [attrs putWithId:@"orderSet" withId:JavaLangInteger_valueOfWithInt_(++orderSet_)];
  (void) [attrs putWithId:@"value" withId:JavaLangBoolean_valueOfWithBoolean_(value)];
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, "LASPagerTabStripImpl_PagerTabStripCommandBuilder;", 0x1, 1, 2, -1, -1, -1, -1 },
    { NULL, "LASPagerTabStripImpl_PagerTabStripCommandBuilder;", 0x1, 3, 4, -1, -1, -1, -1 },
    { NULL, "LASPagerTabStripImpl_PagerTabStripCommandBuilder;", 0x1, 5, 6, -1, -1, -1, -1 },
    { NULL, "LASPagerTabStripImpl_PagerTabStripCommandBuilder;", 0x1, 7, 4, -1, -1, -1, -1 },
    { NULL, "LASPagerTabStripImpl_PagerTabStripCommandBuilder;", 0x1, 8, 4, -1, -1, -1, -1 },
    { NULL, "LASPagerTabStripImpl_PagerTabStripCommandBuilder;", 0x1, 9, 4, -1, -1, -1, -1 },
    { NULL, "LASPagerTabStripImpl_PagerTabStripCommandBuilder;", 0x1, 10, 4, -1, -1, -1, -1 },
    { NULL, "LASPagerTabStripImpl_PagerTabStripCommandBuilder;", 0x1, 11, 4, -1, -1, -1, -1 },
    { NULL, "LASPagerTabStripImpl_PagerTabStripCommandBuilder;", 0x1, 12, 2, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(initWithASPagerTabStripImpl:);
  methods[1].selector = @selector(executeWithBoolean:);
  methods[2].selector = @selector(setTextSpacingWithNSString:);
  methods[3].selector = @selector(setNonPrimaryAlphaWithFloat:);
  methods[4].selector = @selector(setTextColorWithNSString:);
  methods[5].selector = @selector(setGravityWithNSString:);
  methods[6].selector = @selector(setTextSizeWithNSString:);
  methods[7].selector = @selector(setTextAppearanceWithNSString:);
  methods[8].selector = @selector(setTabIndicatorColorWithNSString:);
  methods[9].selector = @selector(setDrawFullUnderlineWithBoolean:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "this$0_", "LASPagerTabStripImpl;", .constantValue.asLong = 0, 0x1012, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LASPagerTabStripImpl;", "execute", "Z", "setTextSpacing", "LNSString;", "setNonPrimaryAlpha", "F", "setTextColor", "setGravity", "setTextSize", "setTextAppearance", "setTabIndicatorColor", "setDrawFullUnderline", "Lcom/ashera/layout/ViewGroupImpl$ViewGroupCommandBuilder<Lcom/ashera/viewpager/PagerTabStripImpl$PagerTabStripCommandBuilder;>;" };
  static const J2ObjcClassInfo _ASPagerTabStripImpl_PagerTabStripCommandBuilder = { "PagerTabStripCommandBuilder", "com.ashera.viewpager", ptrTable, methods, fields, 7, 0x1, 10, 1, 0, -1, -1, 13, -1 };
  return &_ASPagerTabStripImpl_PagerTabStripCommandBuilder;
}

@end

void ASPagerTabStripImpl_PagerTabStripCommandBuilder_initWithASPagerTabStripImpl_(ASPagerTabStripImpl_PagerTabStripCommandBuilder *self, ASPagerTabStripImpl *outer$) {
  self->this$0_ = outer$;
  ASViewGroupImpl_ViewGroupCommandBuilder_init(self);
}

ASPagerTabStripImpl_PagerTabStripCommandBuilder *new_ASPagerTabStripImpl_PagerTabStripCommandBuilder_initWithASPagerTabStripImpl_(ASPagerTabStripImpl *outer$) {
  J2OBJC_NEW_IMPL(ASPagerTabStripImpl_PagerTabStripCommandBuilder, initWithASPagerTabStripImpl_, outer$)
}

ASPagerTabStripImpl_PagerTabStripCommandBuilder *create_ASPagerTabStripImpl_PagerTabStripCommandBuilder_initWithASPagerTabStripImpl_(ASPagerTabStripImpl *outer$) {
  J2OBJC_CREATE_IMPL(ASPagerTabStripImpl_PagerTabStripCommandBuilder, initWithASPagerTabStripImpl_, outer$)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ASPagerTabStripImpl_PagerTabStripCommandBuilder)

@implementation ASPagerTabStripImpl_PagerTabStripBean

- (instancetype)initWithASPagerTabStripImpl:(ASPagerTabStripImpl *)outer$ {
  ASPagerTabStripImpl_PagerTabStripBean_initWithASPagerTabStripImpl_(self, outer$);
  return self;
}

- (void)setTextSpacingWithNSString:(NSString *)value {
  (void) [((ASPagerTabStripImpl_PagerTabStripCommandBuilder *) nil_chk([((ASPagerTabStripImpl_PagerTabStripCommandBuilder *) nil_chk([((ASPagerTabStripImpl_PagerTabStripCommandBuilder *) nil_chk([this$0_ getBuilder])) reset])) setTextSpacingWithNSString:value])) executeWithBoolean:true];
}

- (void)setNonPrimaryAlphaWithFloat:(jfloat)value {
  (void) [((ASPagerTabStripImpl_PagerTabStripCommandBuilder *) nil_chk([((ASPagerTabStripImpl_PagerTabStripCommandBuilder *) nil_chk([((ASPagerTabStripImpl_PagerTabStripCommandBuilder *) nil_chk([this$0_ getBuilder])) reset])) setNonPrimaryAlphaWithFloat:value])) executeWithBoolean:true];
}

- (void)setTextColorWithNSString:(NSString *)value {
  (void) [((ASPagerTabStripImpl_PagerTabStripCommandBuilder *) nil_chk([((ASPagerTabStripImpl_PagerTabStripCommandBuilder *) nil_chk([((ASPagerTabStripImpl_PagerTabStripCommandBuilder *) nil_chk([this$0_ getBuilder])) reset])) setTextColorWithNSString:value])) executeWithBoolean:true];
}

- (void)setGravityWithNSString:(NSString *)value {
  (void) [((ASPagerTabStripImpl_PagerTabStripCommandBuilder *) nil_chk([((ASPagerTabStripImpl_PagerTabStripCommandBuilder *) nil_chk([((ASPagerTabStripImpl_PagerTabStripCommandBuilder *) nil_chk([this$0_ getBuilder])) reset])) setGravityWithNSString:value])) executeWithBoolean:true];
}

- (void)setTextSizeWithNSString:(NSString *)value {
  (void) [((ASPagerTabStripImpl_PagerTabStripCommandBuilder *) nil_chk([((ASPagerTabStripImpl_PagerTabStripCommandBuilder *) nil_chk([((ASPagerTabStripImpl_PagerTabStripCommandBuilder *) nil_chk([this$0_ getBuilder])) reset])) setTextSizeWithNSString:value])) executeWithBoolean:true];
}

- (void)setTextAppearanceWithNSString:(NSString *)value {
  (void) [((ASPagerTabStripImpl_PagerTabStripCommandBuilder *) nil_chk([((ASPagerTabStripImpl_PagerTabStripCommandBuilder *) nil_chk([((ASPagerTabStripImpl_PagerTabStripCommandBuilder *) nil_chk([this$0_ getBuilder])) reset])) setTextAppearanceWithNSString:value])) executeWithBoolean:true];
}

- (void)setTabIndicatorColorWithNSString:(NSString *)value {
  (void) [((ASPagerTabStripImpl_PagerTabStripCommandBuilder *) nil_chk([((ASPagerTabStripImpl_PagerTabStripCommandBuilder *) nil_chk([((ASPagerTabStripImpl_PagerTabStripCommandBuilder *) nil_chk([this$0_ getBuilder])) reset])) setTabIndicatorColorWithNSString:value])) executeWithBoolean:true];
}

- (void)setDrawFullUnderlineWithBoolean:(jboolean)value {
  (void) [((ASPagerTabStripImpl_PagerTabStripCommandBuilder *) nil_chk([((ASPagerTabStripImpl_PagerTabStripCommandBuilder *) nil_chk([((ASPagerTabStripImpl_PagerTabStripCommandBuilder *) nil_chk([this$0_ getBuilder])) reset])) setDrawFullUnderlineWithBoolean:value])) executeWithBoolean:true];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 1, 2, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 3, 4, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 5, 2, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 6, 2, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 7, 2, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 8, 2, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 9, 2, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 10, 11, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(initWithASPagerTabStripImpl:);
  methods[1].selector = @selector(setTextSpacingWithNSString:);
  methods[2].selector = @selector(setNonPrimaryAlphaWithFloat:);
  methods[3].selector = @selector(setTextColorWithNSString:);
  methods[4].selector = @selector(setGravityWithNSString:);
  methods[5].selector = @selector(setTextSizeWithNSString:);
  methods[6].selector = @selector(setTextAppearanceWithNSString:);
  methods[7].selector = @selector(setTabIndicatorColorWithNSString:);
  methods[8].selector = @selector(setDrawFullUnderlineWithBoolean:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "this$0_", "LASPagerTabStripImpl;", .constantValue.asLong = 0, 0x1012, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LASPagerTabStripImpl;", "setTextSpacing", "LNSString;", "setNonPrimaryAlpha", "F", "setTextColor", "setGravity", "setTextSize", "setTextAppearance", "setTabIndicatorColor", "setDrawFullUnderline", "Z" };
  static const J2ObjcClassInfo _ASPagerTabStripImpl_PagerTabStripBean = { "PagerTabStripBean", "com.ashera.viewpager", ptrTable, methods, fields, 7, 0x1, 9, 1, 0, -1, -1, -1, -1 };
  return &_ASPagerTabStripImpl_PagerTabStripBean;
}

@end

void ASPagerTabStripImpl_PagerTabStripBean_initWithASPagerTabStripImpl_(ASPagerTabStripImpl_PagerTabStripBean *self, ASPagerTabStripImpl *outer$) {
  self->this$0_ = outer$;
  ASViewGroupImpl_ViewGroupBean_initWithASIWidget_(self, outer$);
}

ASPagerTabStripImpl_PagerTabStripBean *new_ASPagerTabStripImpl_PagerTabStripBean_initWithASPagerTabStripImpl_(ASPagerTabStripImpl *outer$) {
  J2OBJC_NEW_IMPL(ASPagerTabStripImpl_PagerTabStripBean, initWithASPagerTabStripImpl_, outer$)
}

ASPagerTabStripImpl_PagerTabStripBean *create_ASPagerTabStripImpl_PagerTabStripBean_initWithASPagerTabStripImpl_(ASPagerTabStripImpl *outer$) {
  J2OBJC_CREATE_IMPL(ASPagerTabStripImpl_PagerTabStripBean, initWithASPagerTabStripImpl_, outer$)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ASPagerTabStripImpl_PagerTabStripBean)

@implementation ASPagerTabStripImpl_PagerTabStripParamsBean

- (instancetype)initWithASPagerTabStripImpl:(ASPagerTabStripImpl *)outer$ {
  ASPagerTabStripImpl_PagerTabStripParamsBean_initWithASPagerTabStripImpl_(self, outer$);
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(initWithASPagerTabStripImpl:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "LASPagerTabStripImpl;" };
  static const J2ObjcClassInfo _ASPagerTabStripImpl_PagerTabStripParamsBean = { "PagerTabStripParamsBean", "com.ashera.viewpager", ptrTable, methods, NULL, 7, 0x1, 1, 0, 0, -1, -1, -1, -1 };
  return &_ASPagerTabStripImpl_PagerTabStripParamsBean;
}

@end

void ASPagerTabStripImpl_PagerTabStripParamsBean_initWithASPagerTabStripImpl_(ASPagerTabStripImpl_PagerTabStripParamsBean *self, ASPagerTabStripImpl *outer$) {
  ASViewGroupImpl_ViewGroupParamsBean_init(self);
}

ASPagerTabStripImpl_PagerTabStripParamsBean *new_ASPagerTabStripImpl_PagerTabStripParamsBean_initWithASPagerTabStripImpl_(ASPagerTabStripImpl *outer$) {
  J2OBJC_NEW_IMPL(ASPagerTabStripImpl_PagerTabStripParamsBean, initWithASPagerTabStripImpl_, outer$)
}

ASPagerTabStripImpl_PagerTabStripParamsBean *create_ASPagerTabStripImpl_PagerTabStripParamsBean_initWithASPagerTabStripImpl_(ASPagerTabStripImpl *outer$) {
  J2OBJC_CREATE_IMPL(ASPagerTabStripImpl_PagerTabStripParamsBean, initWithASPagerTabStripImpl_, outer$)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ASPagerTabStripImpl_PagerTabStripParamsBean)

@implementation ASPagerTabStripImpl_PagerTabStripCommandParamsBuilder

- (instancetype)initWithASPagerTabStripImpl:(ASPagerTabStripImpl *)outer$ {
  ASPagerTabStripImpl_PagerTabStripCommandParamsBuilder_initWithASPagerTabStripImpl_(self, outer$);
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(initWithASPagerTabStripImpl:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "LASPagerTabStripImpl;", "Lcom/ashera/layout/ViewGroupImpl$ViewGroupCommandParamsBuilder<Lcom/ashera/viewpager/PagerTabStripImpl$PagerTabStripCommandParamsBuilder;>;" };
  static const J2ObjcClassInfo _ASPagerTabStripImpl_PagerTabStripCommandParamsBuilder = { "PagerTabStripCommandParamsBuilder", "com.ashera.viewpager", ptrTable, methods, NULL, 7, 0x1, 1, 0, 0, -1, -1, 1, -1 };
  return &_ASPagerTabStripImpl_PagerTabStripCommandParamsBuilder;
}

@end

void ASPagerTabStripImpl_PagerTabStripCommandParamsBuilder_initWithASPagerTabStripImpl_(ASPagerTabStripImpl_PagerTabStripCommandParamsBuilder *self, ASPagerTabStripImpl *outer$) {
  ASViewGroupImpl_ViewGroupCommandParamsBuilder_init(self);
}

ASPagerTabStripImpl_PagerTabStripCommandParamsBuilder *new_ASPagerTabStripImpl_PagerTabStripCommandParamsBuilder_initWithASPagerTabStripImpl_(ASPagerTabStripImpl *outer$) {
  J2OBJC_NEW_IMPL(ASPagerTabStripImpl_PagerTabStripCommandParamsBuilder, initWithASPagerTabStripImpl_, outer$)
}

ASPagerTabStripImpl_PagerTabStripCommandParamsBuilder *create_ASPagerTabStripImpl_PagerTabStripCommandParamsBuilder_initWithASPagerTabStripImpl_(ASPagerTabStripImpl *outer$) {
  J2OBJC_CREATE_IMPL(ASPagerTabStripImpl_PagerTabStripCommandParamsBuilder, initWithASPagerTabStripImpl_, outer$)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ASPagerTabStripImpl_PagerTabStripCommandParamsBuilder)

@implementation ASPagerTabStripImpl_$Lambda$1

- (void)run {
  ASViewGroupImpl_nativeRemoveViewWithASIWidget_(val$widget_);
}

@end

void ASPagerTabStripImpl_$Lambda$1_initWithASIWidget_(ASPagerTabStripImpl_$Lambda$1 *self, id<ASIWidget> capture$0) {
  self->val$widget_ = capture$0;
  NSObject_init(self);
}

ASPagerTabStripImpl_$Lambda$1 *new_ASPagerTabStripImpl_$Lambda$1_initWithASIWidget_(id<ASIWidget> capture$0) {
  J2OBJC_NEW_IMPL(ASPagerTabStripImpl_$Lambda$1, initWithASIWidget_, capture$0)
}

ASPagerTabStripImpl_$Lambda$1 *create_ASPagerTabStripImpl_$Lambda$1_initWithASIWidget_(id<ASIWidget> capture$0) {
  J2OBJC_CREATE_IMPL(ASPagerTabStripImpl_$Lambda$1, initWithASIWidget_, capture$0)
}
