//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSViewPagerPlugin\src\main\java\com\ashera\viewpager\ViewPagerImpl.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ViewPagerImpl")
#ifdef RESTRICT_ViewPagerImpl
#define INCLUDE_ALL_ViewPagerImpl 0
#else
#define INCLUDE_ALL_ViewPagerImpl 1
#endif
#undef RESTRICT_ViewPagerImpl

#if !defined (ASViewPagerImpl_) && (INCLUDE_ALL_ViewPagerImpl || defined(INCLUDE_ASViewPagerImpl))
#define ASViewPagerImpl_

#define RESTRICT_BaseHasWidgets 1
#define INCLUDE_ASBaseHasWidgets 1
#include "BaseHasWidgets.h"

@class ASLoopParam;
@class ASWidgetAttribute;
@class IOSClass;
@protocol ASIFragment;
@protocol ASILifeCycleDecorator;
@protocol ASIWidget;
@protocol JavaUtilMap;

@interface ASViewPagerImpl : ASBaseHasWidgets
@property id uiView;

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)localname;

- (instancetype)initWithNSString:(NSString *)groupName
                    withNSString:(NSString *)localname;

- (void)addWithASIWidget:(id<ASIWidget>)w
                 withInt:(jint)index;

- (id)asNativeWidget;

- (id)asWidget;

- (jboolean)checkIosVersionWithNSString:(NSString *)v;

- (void)createWithASIFragment:(id<ASIFragment>)fragment
              withJavaUtilMap:(id<JavaUtilMap>)params;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
              withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (id)getChildAttributeWithASIWidget:(id<ASIWidget>)w
               withASWidgetAttribute:(ASWidgetAttribute *)key;

- (IOSClass *)getViewClass;

- (void)initialized OBJC_METHOD_FAMILY_NONE;

- (void)invalidate;

- (void)loadAttributesWithNSString:(NSString *)localName;

- (id<ASIWidget>)newInstance OBJC_METHOD_FAMILY_NONE;

- (jboolean)removeWithInt:(jint)index;

- (jboolean)removeWithASIWidget:(id<ASIWidget>)w;

- (void)requestLayout;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue
                withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (void)setChildAttributeWithASIWidget:(id<ASIWidget>)w
                 withASWidgetAttribute:(ASWidgetAttribute *)key
                          withNSString:(NSString *)strValue
                                withId:(id)objValue;

- (void)setIdWithNSString:(NSString *)id_;

- (void)setVisibleWithBoolean:(jboolean)b;

#pragma mark Protected

- (void)addItemToParentWithInt:(jint)index
                  withNSString:(NSString *)id_
               withASLoopParam:(ASLoopParam *)childModel;

@end

J2OBJC_EMPTY_STATIC_INIT(ASViewPagerImpl)

inline NSString *ASViewPagerImpl_get_LOCAL_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASViewPagerImpl_LOCAL_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASViewPagerImpl, LOCAL_NAME, NSString *)

inline NSString *ASViewPagerImpl_get_GROUP_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASViewPagerImpl_GROUP_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASViewPagerImpl, GROUP_NAME, NSString *)

FOUNDATION_EXPORT void ASViewPagerImpl_init(ASViewPagerImpl *self);

FOUNDATION_EXPORT ASViewPagerImpl *new_ASViewPagerImpl_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASViewPagerImpl *create_ASViewPagerImpl_init(void);

FOUNDATION_EXPORT void ASViewPagerImpl_initWithNSString_(ASViewPagerImpl *self, NSString *localname);

FOUNDATION_EXPORT ASViewPagerImpl *new_ASViewPagerImpl_initWithNSString_(NSString *localname) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASViewPagerImpl *create_ASViewPagerImpl_initWithNSString_(NSString *localname);

FOUNDATION_EXPORT void ASViewPagerImpl_initWithNSString_withNSString_(ASViewPagerImpl *self, NSString *groupName, NSString *localname);

FOUNDATION_EXPORT ASViewPagerImpl *new_ASViewPagerImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASViewPagerImpl *create_ASViewPagerImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname);

J2OBJC_TYPE_LITERAL_HEADER(ASViewPagerImpl)

@compatibility_alias ComAsheraViewpagerViewPagerImpl ASViewPagerImpl;

#endif

#if !defined (ASViewPagerImpl_ViewPagerExt_) && (INCLUDE_ALL_ViewPagerImpl || defined(INCLUDE_ASViewPagerImpl_ViewPagerExt))
#define ASViewPagerImpl_ViewPagerExt_

#define RESTRICT_ViewPager 1
#define INCLUDE_ADXViewPager 1
#include "ViewPager.h"

#define RESTRICT_ILifeCycleDecorator 1
#define INCLUDE_ASILifeCycleDecorator 1
#include "ILifeCycleDecorator.h"

#define RESTRICT_IMaxDimension 1
#define INCLUDE_ASIMaxDimension 1
#include "IMaxDimension.h"

@class ADRect;
@class ADView;
@class ASViewPagerImpl;
@class ASWidgetAttribute;
@class IOSIntArray;
@class IOSObjectArray;
@protocol ASIWidget;
@protocol JavaUtilList;

@interface ASViewPagerImpl_ViewPagerExt : ADXViewPager < ASILifeCycleDecorator, ASIMaxDimension >

#pragma mark Public

- (instancetype)initWithASViewPagerImpl:(ASViewPagerImpl *)outer$;

- (void)drawableStateChanged;

- (void)endViewTransitionWithADView:(ADView *)view;

- (void)executeWithNSString:(NSString *)method
          withNSObjectArray:(IOSObjectArray *)canvas;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute;

- (void)getLocationOnScreenWithIntArray:(IOSIntArray *)appScreenLocation;

- (jint)getMaxHeight;

- (jint)getMaxWidth;

- (id<JavaUtilList>)getMethods;

- (jint)getScrollX;

- (id<ASIWidget>)getWidget;

- (void)getWindowVisibleDisplayFrameWithADRect:(ADRect *)displayFrame;

- (ADView *)inflateViewWithNSString:(NSString *)layout;

- (void)initialized OBJC_METHOD_FAMILY_NONE;

- (id<ASILifeCycleDecorator>)newInstanceWithASIWidget:(id<ASIWidget>)widget OBJC_METHOD_FAMILY_NONE;

- (void)offsetLeftAndRightWithInt:(jint)offset;

- (void)offsetTopAndBottomWithInt:(jint)offset;

- (void)onMeasureWithInt:(jint)widthMeasureSpec
                 withInt:(jint)heightMeasureSpec;

- (void)remeasure;

- (void)removeFromParent;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue;

- (void)setMaxHeightWithInt:(jint)height;

- (void)setMaxWidthWithInt:(jint)width;

- (void)setMyAttributeWithNSString:(NSString *)name
                            withId:(id)value;

- (void)setState0WithId:(id)value;

- (void)setState1WithId:(id)value;

- (void)setState2WithId:(id)value;

- (void)setState3WithId:(id)value;

- (void)setState4WithId:(id)value;

- (void)setVisibilityWithInt:(jint)visibility;

- (void)state0;

- (void)state1;

- (void)state2;

- (void)state3;

- (void)state4;

- (void)stateNo;

- (void)stateYes;

- (void)updateMeasuredDimensionWithInt:(jint)width
                               withInt:(jint)height;

#pragma mark Protected

- (void)onLayoutWithBoolean:(jboolean)changed
                    withInt:(jint)l
                    withInt:(jint)t
                    withInt:(jint)r
                    withInt:(jint)b;

- (void)scrollToWithInt:(jint)x
                withInt:(jint)y;

- (void)smoothScrollToWithInt:(jint)x
                      withInt:(jint)y
                      withInt:(jint)velocity;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASViewPagerImpl_ViewPagerExt)

FOUNDATION_EXPORT void ASViewPagerImpl_ViewPagerExt_initWithASViewPagerImpl_(ASViewPagerImpl_ViewPagerExt *self, ASViewPagerImpl *outer$);

FOUNDATION_EXPORT ASViewPagerImpl_ViewPagerExt *new_ASViewPagerImpl_ViewPagerExt_initWithASViewPagerImpl_(ASViewPagerImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASViewPagerImpl_ViewPagerExt *create_ASViewPagerImpl_ViewPagerExt_initWithASViewPagerImpl_(ASViewPagerImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASViewPagerImpl_ViewPagerExt)

#endif

#if !defined (ASViewPagerImpl_CustomPagerAdapter_) && (INCLUDE_ALL_ViewPagerImpl || defined(INCLUDE_ASViewPagerImpl_CustomPagerAdapter))
#define ASViewPagerImpl_CustomPagerAdapter_

#define RESTRICT_PagerAdapter 1
#define INCLUDE_ADXPagerAdapter 1
#include "PagerAdapter.h"

@class ADView;
@class ADViewGroup;
@class ASViewPagerImpl;
@protocol JavaLangCharSequence;

@interface ASViewPagerImpl_CustomPagerAdapter : ADXPagerAdapter

#pragma mark Public

- (instancetype)initWithASViewPagerImpl:(ASViewPagerImpl *)outer$;

- (void)destroyItemWithADViewGroup:(ADViewGroup *)collection
                           withInt:(jint)position
                            withId:(id)view;

- (jint)getCount;

- (id<JavaLangCharSequence>)getPageTitleWithInt:(jint)position;

- (jfloat)getPageWidthWithInt:(jint)position;

- (id)instantiateItemWithADViewGroup:(ADViewGroup *)collection
                             withInt:(jint)position;

- (jboolean)isViewFromObjectWithADView:(ADView *)view
                                withId:(id)object;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASViewPagerImpl_CustomPagerAdapter)

FOUNDATION_EXPORT void ASViewPagerImpl_CustomPagerAdapter_initWithASViewPagerImpl_(ASViewPagerImpl_CustomPagerAdapter *self, ASViewPagerImpl *outer$);

FOUNDATION_EXPORT ASViewPagerImpl_CustomPagerAdapter *new_ASViewPagerImpl_CustomPagerAdapter_initWithASViewPagerImpl_(ASViewPagerImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASViewPagerImpl_CustomPagerAdapter *create_ASViewPagerImpl_CustomPagerAdapter_initWithASViewPagerImpl_(ASViewPagerImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASViewPagerImpl_CustomPagerAdapter)

#endif

#pragma pop_macro("INCLUDE_ALL_ViewPagerImpl")
