//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSViewPagerPlugin\src\main\java\com\ashera\viewpager\ViewPagerPlugin.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ViewPagerPlugin")
#ifdef RESTRICT_ViewPagerPlugin
#define INCLUDE_ALL_ViewPagerPlugin 0
#else
#define INCLUDE_ALL_ViewPagerPlugin 1
#endif
#undef RESTRICT_ViewPagerPlugin

#if !defined (ASViewPagerPlugin_) && (INCLUDE_ALL_ViewPagerPlugin || defined(INCLUDE_ASViewPagerPlugin))
#define ASViewPagerPlugin_

@interface ASViewPagerPlugin : NSObject

#pragma mark Public

- (instancetype)init;

+ (void)initPlugin OBJC_METHOD_FAMILY_NONE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASViewPagerPlugin)

FOUNDATION_EXPORT void ASViewPagerPlugin_init(ASViewPagerPlugin *self);

FOUNDATION_EXPORT ASViewPagerPlugin *new_ASViewPagerPlugin_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASViewPagerPlugin *create_ASViewPagerPlugin_init(void);

FOUNDATION_EXPORT void ASViewPagerPlugin_initPlugin(void);

J2OBJC_TYPE_LITERAL_HEADER(ASViewPagerPlugin)

@compatibility_alias ComAsheraViewpagerViewPagerPlugin ASViewPagerPlugin;


#endif

#pragma pop_macro("INCLUDE_ALL_ViewPagerPlugin")
