//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSViewPagerPlugin\src\main\java\com\ashera\viewpager\ViewPagerImpl.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ViewPagerImpl")
#ifdef RESTRICT_ViewPagerImpl
#define INCLUDE_ALL_ViewPagerImpl 0
#else
#define INCLUDE_ALL_ViewPagerImpl 1
#endif
#undef RESTRICT_ViewPagerImpl

#if !defined (ASViewPagerImpl_) && (INCLUDE_ALL_ViewPagerImpl || defined(INCLUDE_ASViewPagerImpl))
#define ASViewPagerImpl_

#define RESTRICT_BaseHasWidgets 1
#define INCLUDE_ASBaseHasWidgets 1
#include "BaseHasWidgets.h"

@class ASLoopParam;
@class ASViewPagerImpl_ViewPagerBean;
@class ASViewPagerImpl_ViewPagerCommandBuilder;
@class ASViewPagerImpl_ViewPagerCommandParamsBuilder;
@class ASViewPagerImpl_ViewPagerParamsBean;
@class ASWidgetAttribute;
@class IOSClass;
@protocol ASIFragment;
@protocol ASILifeCycleDecorator;
@protocol ASIWidget;
@protocol JavaUtilMap;

@interface ASViewPagerImpl : ASBaseHasWidgets
@property id uiView;

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)localname;

- (instancetype)initWithNSString:(NSString *)groupName
                    withNSString:(NSString *)localname;

- (void)addWithASIWidget:(id<ASIWidget>)w
                 withInt:(jint)index;

- (id)asNativeWidget;

- (id)asWidget;

- (jboolean)checkIosVersionWithNSString:(NSString *)v;

- (void)createWithASIFragment:(id<ASIFragment>)fragment
              withJavaUtilMap:(id<JavaUtilMap>)params;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
              withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (ASViewPagerImpl_ViewPagerBean *)getBean;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)getBuilder;

- (id)getChildAttributeWithASIWidget:(id<ASIWidget>)w
               withASWidgetAttribute:(ASWidgetAttribute *)key;

- (ASViewPagerImpl_ViewPagerParamsBean *)getParamsBean;

- (ASViewPagerImpl_ViewPagerCommandParamsBuilder *)getParamsBuilder;

- (id)getPluginWithNSString:(NSString *)plugin;

- (IOSClass *)getViewClass;

- (void)initialized OBJC_METHOD_FAMILY_NONE;

- (void)invalidate;

- (void)loadAttributesWithNSString:(NSString *)localName;

- (id<ASIWidget>)newInstance OBJC_METHOD_FAMILY_NONE;

- (jboolean)removeWithInt:(jint)index;

- (jboolean)removeWithASIWidget:(id<ASIWidget>)w;

- (void)requestLayout;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue
                withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (void)setChildAttributeWithASIWidget:(id<ASIWidget>)w
                 withASWidgetAttribute:(ASWidgetAttribute *)key
                          withNSString:(NSString *)strValue
                                withId:(id)objValue;

- (void)setIdWithNSString:(NSString *)id_;

- (void)setVisibleWithBoolean:(jboolean)b;

#pragma mark Protected

- (void)addItemToParentWithInt:(jint)index
                  withNSString:(NSString *)id_
               withASLoopParam:(ASLoopParam *)childModel;

@end

J2OBJC_EMPTY_STATIC_INIT(ASViewPagerImpl)

inline NSString *ASViewPagerImpl_get_LOCAL_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASViewPagerImpl_LOCAL_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASViewPagerImpl, LOCAL_NAME, NSString *)

inline NSString *ASViewPagerImpl_get_GROUP_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASViewPagerImpl_GROUP_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASViewPagerImpl, GROUP_NAME, NSString *)

FOUNDATION_EXPORT void ASViewPagerImpl_init(ASViewPagerImpl *self);

FOUNDATION_EXPORT ASViewPagerImpl *new_ASViewPagerImpl_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASViewPagerImpl *create_ASViewPagerImpl_init(void);

FOUNDATION_EXPORT void ASViewPagerImpl_initWithNSString_(ASViewPagerImpl *self, NSString *localname);

FOUNDATION_EXPORT ASViewPagerImpl *new_ASViewPagerImpl_initWithNSString_(NSString *localname) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASViewPagerImpl *create_ASViewPagerImpl_initWithNSString_(NSString *localname);

FOUNDATION_EXPORT void ASViewPagerImpl_initWithNSString_withNSString_(ASViewPagerImpl *self, NSString *groupName, NSString *localname);

FOUNDATION_EXPORT ASViewPagerImpl *new_ASViewPagerImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASViewPagerImpl *create_ASViewPagerImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname);

J2OBJC_TYPE_LITERAL_HEADER(ASViewPagerImpl)

@compatibility_alias ComAsheraViewpagerViewPagerImpl ASViewPagerImpl;

#endif

#if !defined (ASViewPagerImpl_ViewPagerExt_) && (INCLUDE_ALL_ViewPagerImpl || defined(INCLUDE_ASViewPagerImpl_ViewPagerExt))
#define ASViewPagerImpl_ViewPagerExt_

#define RESTRICT_ViewPager 1
#define INCLUDE_ASViewPager 1
#include "ViewPager.h"

#define RESTRICT_ILifeCycleDecorator 1
#define INCLUDE_ASILifeCycleDecorator 1
#include "ILifeCycleDecorator.h"

#define RESTRICT_IMaxDimension 1
#define INCLUDE_ASIMaxDimension 1
#include "IMaxDimension.h"

@class ADRect;
@class ADView;
@class ASViewPagerImpl;
@class ASWidgetAttribute;
@class IOSIntArray;
@class IOSObjectArray;
@protocol ASIWidget;
@protocol JavaUtilList;

@interface ASViewPagerImpl_ViewPagerExt : ASViewPager < ASILifeCycleDecorator, ASIMaxDimension >

#pragma mark Public

- (instancetype)initWithASViewPagerImpl:(ASViewPagerImpl *)outer$;

- (void)drawableStateChanged;

- (void)executeWithNSString:(NSString *)method
          withNSObjectArray:(IOSObjectArray *)canvas;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute;

- (void)getLocationOnScreenWithIntArray:(IOSIntArray *)appScreenLocation;

- (jint)getMaxHeight;

- (jint)getMaxWidth;

- (id<JavaUtilList>)getMethods;

- (jint)getScrollX;

- (void)getWindowVisibleDisplayFrameWithADRect:(ADRect *)displayFrame;

- (ADView *)inflateViewWithNSString:(NSString *)layout;

- (void)initialized OBJC_METHOD_FAMILY_NONE;

- (id<ASILifeCycleDecorator>)newInstanceWithASIWidget:(id<ASIWidget>)widget OBJC_METHOD_FAMILY_NONE;

- (void)offsetLeftAndRightWithInt:(jint)offset;

- (void)offsetTopAndBottomWithInt:(jint)offset;

- (void)onMeasureWithInt:(jint)widthMeasureSpec
                 withInt:(jint)heightMeasureSpec;

- (void)remeasure;

- (void)removeFromParent;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue;

- (void)setMaxHeightWithInt:(jint)height;

- (void)setMaxWidthWithInt:(jint)width;

- (void)setMyAttributeWithNSString:(NSString *)name
                            withId:(id)value;

- (void)setVisibilityWithInt:(jint)visibility;

- (void)updateMeasuredDimensionWithInt:(jint)width
                               withInt:(jint)height;

#pragma mark Protected

- (void)onLayoutWithBoolean:(jboolean)changed
                    withInt:(jint)l
                    withInt:(jint)t
                    withInt:(jint)r
                    withInt:(jint)b;

- (void)scrollToWithInt:(jint)x
                withInt:(jint)y;

- (void)smoothScrollToWithInt:(jint)x
                      withInt:(jint)y
                      withInt:(jint)velocity;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASViewPagerImpl_ViewPagerExt)

FOUNDATION_EXPORT void ASViewPagerImpl_ViewPagerExt_initWithASViewPagerImpl_(ASViewPagerImpl_ViewPagerExt *self, ASViewPagerImpl *outer$);

FOUNDATION_EXPORT ASViewPagerImpl_ViewPagerExt *new_ASViewPagerImpl_ViewPagerExt_initWithASViewPagerImpl_(ASViewPagerImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASViewPagerImpl_ViewPagerExt *create_ASViewPagerImpl_ViewPagerExt_initWithASViewPagerImpl_(ASViewPagerImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASViewPagerImpl_ViewPagerExt)

#endif

#if !defined (ASViewPagerImpl_CustomPagerAdapter_) && (INCLUDE_ALL_ViewPagerImpl || defined(INCLUDE_ASViewPagerImpl_CustomPagerAdapter))
#define ASViewPagerImpl_CustomPagerAdapter_

#define RESTRICT_PagerAdapter 1
#define INCLUDE_ASPagerAdapter 1
#include "PagerAdapter.h"

@class ADView;
@class ADViewGroup;
@class ASViewPagerImpl;
@protocol JavaLangCharSequence;

@interface ASViewPagerImpl_CustomPagerAdapter : ASPagerAdapter

#pragma mark Public

- (instancetype)initWithASViewPagerImpl:(ASViewPagerImpl *)outer$;

- (void)destroyItemWithADViewGroup:(ADViewGroup *)collection
                           withInt:(jint)position
                            withId:(id)view;

- (jint)getCount;

- (id<JavaLangCharSequence>)getPageTitleWithInt:(jint)position;

- (jfloat)getPageWidthWithInt:(jint)position;

- (id)instantiateItemWithADViewGroup:(ADViewGroup *)collection
                             withInt:(jint)position;

- (jboolean)isViewFromObjectWithADView:(ADView *)view
                                withId:(id)object;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASViewPagerImpl_CustomPagerAdapter)

FOUNDATION_EXPORT void ASViewPagerImpl_CustomPagerAdapter_initWithASViewPagerImpl_(ASViewPagerImpl_CustomPagerAdapter *self, ASViewPagerImpl *outer$);

FOUNDATION_EXPORT ASViewPagerImpl_CustomPagerAdapter *new_ASViewPagerImpl_CustomPagerAdapter_initWithASViewPagerImpl_(ASViewPagerImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASViewPagerImpl_CustomPagerAdapter *create_ASViewPagerImpl_CustomPagerAdapter_initWithASViewPagerImpl_(ASViewPagerImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASViewPagerImpl_CustomPagerAdapter)

#endif

#if !defined (ASViewPagerImpl_ViewPagerCommandBuilder_) && (INCLUDE_ALL_ViewPagerImpl || defined(INCLUDE_ASViewPagerImpl_ViewPagerCommandBuilder))
#define ASViewPagerImpl_ViewPagerCommandBuilder_

#define RESTRICT_ViewGroupImpl 1
#define INCLUDE_ASViewGroupImpl_ViewGroupCommandBuilder 1
#include "ViewGroupImpl.h"

@class ASViewPagerImpl;

@interface ASViewPagerImpl_ViewPagerCommandBuilder : ASViewGroupImpl_ViewGroupCommandBuilder

#pragma mark Public

- (instancetype)initWithASViewPagerImpl:(ASViewPagerImpl *)outer$;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)addAllModelWithId:(id)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)addModelByIndexWithId:(id)arg0
                                                            withId:(id)arg1;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)addModelWithId:(id)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)executeWithBoolean:(jboolean)setter;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)invalidate;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)notifyDataSetChangedWithBoolean:(jboolean)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)refreshUiFromModelWithNSString:(NSString *)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)removeModelAtIndexWithInt:(jint)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)removeModelByIdWithNSString:(NSString *)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)requestLayout;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)reset;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setAddStatesFromChildrenWithBoolean:(jboolean)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setAlphaWithFloat:(jfloat)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setAsDragSourceWithNSString:(NSString *)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setAttributeUnderTestWithNSString:(NSString *)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setBackgroundRepeatWithNSString:(NSString *)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setBackgroundTintModeWithNSString:(NSString *)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setBackgroundTintWithNSString:(NSString *)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setBackgroundWithNSString:(NSString *)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setChildXmlWithNSString:(NSString *)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setClickableWithBoolean:(jboolean)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setClipChildrenWithBoolean:(jboolean)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setClipToPaddingWithBoolean:(jboolean)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setContentDescriptionWithNSString:(NSString *)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setCurrentItemWithInt:(jint)value;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setCustomErrorMessageKeysWithNSString:(NSString *)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setCustomErrorMessageValuesWithNSString:(NSString *)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setDuplicateParentStateWithBoolean:(jboolean)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setEnabledWithBoolean:(jboolean)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setErrorStyleWithNSString:(NSString *)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setFocusableWithBoolean:(jboolean)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setForegroundGravityWithNSString:(NSString *)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setForegroundRepeatWithNSString:(NSString *)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setForegroundTintModeWithNSString:(NSString *)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setForegroundTintWithNSString:(NSString *)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setForegroundWithNSString:(NSString *)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setIdWithNSString:(NSString *)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setInvalidateOnFrameChangeWithBoolean:(jboolean)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setIosAccessibilityHintWithNSString:(NSString *)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setIosAccessibilityIgnoresInvertColorsWithBoolean:(jboolean)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setIosAccessibilityLabelWithNSString:(NSString *)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setIosAccessibilityTraitsWithNSString:(NSString *)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setIosAccessibilityValueWithNSString:(NSString *)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setIosAlphaWithFloat:(jfloat)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setIosAutoresizesSubviewsWithBoolean:(jboolean)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setIosBackgroundColorWithNSString:(NSString *)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setIosClearsContextBeforeDrawingWithBoolean:(jboolean)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setIosClipsToBoundsWithBoolean:(jboolean)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setIosContentScaleFactorWithFloat:(jfloat)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setIosInsetsLayoutMarginsFromSafeAreaWithBoolean:(jboolean)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setIosIsAccessibilityElementWithBoolean:(jboolean)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setIosIsExclusiveTouchWithBoolean:(jboolean)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setIosIsHiddenWithBoolean:(jboolean)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setIosIsMultipleTouchEnabledWithBoolean:(jboolean)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setIosIsOpaqueWithBoolean:(jboolean)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setIosIsUserInteractionEnabledWithBoolean:(jboolean)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setIosLargeContentImageWithNSString:(NSString *)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setIosLargeContentTitleWithNSString:(NSString *)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setIosLayerBorderColorWithNSString:(NSString *)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setIosLayerBorderWidthWithNSString:(NSString *)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setIosLayerCornerRadiusWithNSString:(NSString *)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setIosLayerMasksToBoundsWithBoolean:(jboolean)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setIosPreservesSuperviewLayoutMarginsWithBoolean:(jboolean)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setIosRestorationIdentifierWithNSString:(NSString *)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setIosScalesLargeContentImageWithBoolean:(jboolean)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setIosShowsLargeContentViewerWithBoolean:(jboolean)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setIosTagWithInt:(jint)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setIosTintColorWithNSString:(NSString *)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setIosTranslatesAutoresizingMaskIntoConstraintsWithBoolean:(jboolean)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setKeepScreenOnWithBoolean:(jboolean)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setLayoutDirectionWithNSString:(NSString *)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setLayoutModeWithNSString:(NSString *)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setListitemWithNSString:(NSString *)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setLongClickableWithBoolean:(jboolean)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setMaxHeightWithNSString:(NSString *)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setMaxWidthWithNSString:(NSString *)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setMinHeightWithNSString:(NSString *)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setMinWidthWithNSString:(NSString *)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setModelDescPathWithNSString:(NSString *)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setModelForWithNSString:(NSString *)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setModelIdPathWithNSString:(NSString *)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setModelParamWithNSString:(NSString *)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setModelPojoToUiParamsWithNSString:(NSString *)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setModelPojoToUiWithNSString:(NSString *)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setModelSyncEventsWithNSString:(NSString *)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setModelUiToPojoEventIdsWithNSString:(NSString *)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setModelUiToPojoWithNSString:(NSString *)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setOffscreenPageLimitWithInt:(jint)value;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setOnChildViewAddedWithNSString:(NSString *)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setOnChildViewRemovedWithNSString:(NSString *)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setOnClickWithNSString:(NSString *)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setOnDragWithNSString:(NSString *)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setOnKeyWithNSString:(NSString *)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setOnLongClickWithNSString:(NSString *)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setOnPageScrolledWithNSString:(NSString *)value;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setOnPageScrollStateChangeWithNSString:(NSString *)value;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setOnPageSelectedWithNSString:(NSString *)value;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setOnSwipedWithNSString:(NSString *)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setOnTouchWithNSString:(NSString *)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setOutsideTouchableWithBoolean:(jboolean)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setPaddingBottomWithNSString:(NSString *)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setPaddingEndWithNSString:(NSString *)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setPaddingHorizontalWithNSString:(NSString *)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setPaddingLeftWithNSString:(NSString *)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setPaddingRightWithNSString:(NSString *)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setPaddingStartWithNSString:(NSString *)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setPaddingTopWithNSString:(NSString *)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setPaddingVerticalWithNSString:(NSString *)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setPaddingWithNSString:(NSString *)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setPageMarginWithNSString:(NSString *)value;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setPageMarginDrawableWithNSString:(NSString *)value;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setPageTitlesWithNSString:(NSString *)value;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setPageWidthWithFloat:(jfloat)value;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setRotationWithFloat:(jfloat)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setRotationXWithFloat:(jfloat)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setRotationYWithFloat:(jfloat)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setScaleXWithFloat:(jfloat)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setScaleYWithFloat:(jfloat)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setSelectedWithBoolean:(jboolean)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setStyleWithNSString:(NSString *)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setTextAlignmentWithNSString:(NSString *)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setTextDirectionWithNSString:(NSString *)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setTransformPivotXWithNSString:(NSString *)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setTransformPivotYWithNSString:(NSString *)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setTranslationXWithNSString:(NSString *)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setTranslationYWithNSString:(NSString *)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setTranslationZWithNSString:(NSString *)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setV_maxlengthWithNSString:(NSString *)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setV_maxWithNSString:(NSString *)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setV_minlengthWithNSString:(NSString *)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setV_minWithNSString:(NSString *)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setV_patternWithNSString:(NSString *)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setV_requiredWithNSString:(NSString *)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setV_typeWithNSString:(NSString *)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setValidationErrorDisplayTypeWithNSString:(NSString *)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setValidationWithNSString:(NSString *)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setVisibilityWithNSString:(NSString *)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)setZIndexWithInt:(jint)arg0;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)tryGetAddStatesFromChildren;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)tryGetAlpha;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)tryGetBackground;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)tryGetBackgroundTint;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)tryGetBackgroundTintMode;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)tryGetClickable;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)tryGetClipChildren;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)tryGetClipToPadding;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)tryGetContentDescription;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)tryGetDuplicateParentState;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)tryGetEnabled;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)tryGetFocusable;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)tryGetForeground;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)tryGetForegroundGravity;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)tryGetForegroundTint;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)tryGetForegroundTintMode;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)tryGetId;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)tryGetIosAccessibilityHint;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)tryGetIosAccessibilityIgnoresInvertColors;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)tryGetIosAccessibilityLabel;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)tryGetIosAccessibilityTraits;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)tryGetIosAccessibilityValue;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)tryGetIosAlpha;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)tryGetIosAutoresizesSubviews;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)tryGetIosBackgroundColor;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)tryGetIosClearsContextBeforeDrawing;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)tryGetIosClipsToBounds;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)tryGetIosContentScaleFactor;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)tryGetIosInsetsLayoutMarginsFromSafeArea;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)tryGetIosIsAccessibilityElement;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)tryGetIosIsExclusiveTouch;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)tryGetIosIsFocused;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)tryGetIosIsHidden;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)tryGetIosIsMultipleTouchEnabled;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)tryGetIosIsOpaque;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)tryGetIosIsUserInteractionEnabled;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)tryGetIosLargeContentImage;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)tryGetIosLargeContentTitle;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)tryGetIosPreservesSuperviewLayoutMargins;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)tryGetIosRestorationIdentifier;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)tryGetIosScalesLargeContentImage;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)tryGetIosShowsLargeContentViewer;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)tryGetIosTag;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)tryGetIosTintColor;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)tryGetIosTranslatesAutoresizingMaskIntoConstraints;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)tryGetKeepScreenOn;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)tryGetLayoutDirection;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)tryGetLayoutMode;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)tryGetLongClickable;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)tryGetMaxHeight;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)tryGetMaxWidth;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)tryGetMinHeight;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)tryGetMinWidth;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)tryGetModelDescPath;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)tryGetModelIdPath;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)tryGetModelParam;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)tryGetModelPojoToUi;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)tryGetModelSyncEvents;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)tryGetModelUiToPojo;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)tryGetPaddingBottom;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)tryGetPaddingEnd;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)tryGetPaddingLeft;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)tryGetPaddingRight;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)tryGetPaddingStart;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)tryGetPaddingTop;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)tryGetRotation;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)tryGetRotationX;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)tryGetRotationY;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)tryGetScaleX;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)tryGetScaleY;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)tryGetSelected;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)tryGetTextAlignment;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)tryGetTextDirection;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)tryGetTransformPivotX;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)tryGetTransformPivotY;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)tryGetTranslationX;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)tryGetTranslationY;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)tryGetTranslationZ;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)tryGetValidateForm;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)tryGetVisibility;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)updateModelDataWithNSString:(NSString *)arg0
                                                                  withId:(id)arg1;

- (ASViewPagerImpl_ViewPagerCommandBuilder *)validateFormWithNSString:(NSString *)arg0;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASViewPagerImpl_ViewPagerCommandBuilder)

FOUNDATION_EXPORT void ASViewPagerImpl_ViewPagerCommandBuilder_initWithASViewPagerImpl_(ASViewPagerImpl_ViewPagerCommandBuilder *self, ASViewPagerImpl *outer$);

FOUNDATION_EXPORT ASViewPagerImpl_ViewPagerCommandBuilder *new_ASViewPagerImpl_ViewPagerCommandBuilder_initWithASViewPagerImpl_(ASViewPagerImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASViewPagerImpl_ViewPagerCommandBuilder *create_ASViewPagerImpl_ViewPagerCommandBuilder_initWithASViewPagerImpl_(ASViewPagerImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASViewPagerImpl_ViewPagerCommandBuilder)

#endif

#if !defined (ASViewPagerImpl_ViewPagerBean_) && (INCLUDE_ALL_ViewPagerImpl || defined(INCLUDE_ASViewPagerImpl_ViewPagerBean))
#define ASViewPagerImpl_ViewPagerBean_

#define RESTRICT_ViewGroupImpl 1
#define INCLUDE_ASViewGroupImpl_ViewGroupBean 1
#include "ViewGroupImpl.h"

@class ASViewPagerImpl;
@protocol ASIWidget;

@interface ASViewPagerImpl_ViewPagerBean : ASViewGroupImpl_ViewGroupBean

#pragma mark Public

- (instancetype)initWithASViewPagerImpl:(ASViewPagerImpl *)outer$;

- (void)setCurrentItemWithInt:(jint)value;

- (void)setOffscreenPageLimitWithInt:(jint)value;

- (void)setOnPageScrolledWithNSString:(NSString *)value;

- (void)setOnPageScrollStateChangeWithNSString:(NSString *)value;

- (void)setOnPageSelectedWithNSString:(NSString *)value;

- (void)setPageMarginWithNSString:(NSString *)value;

- (void)setPageMarginDrawableWithNSString:(NSString *)value;

- (void)setPageTitlesWithNSString:(NSString *)value;

- (void)setPageWidthWithFloat:(jfloat)value;

// Disallowed inherited constructors, do not use.

- (instancetype)initWithASIWidget:(id<ASIWidget>)arg0 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASViewPagerImpl_ViewPagerBean)

FOUNDATION_EXPORT void ASViewPagerImpl_ViewPagerBean_initWithASViewPagerImpl_(ASViewPagerImpl_ViewPagerBean *self, ASViewPagerImpl *outer$);

FOUNDATION_EXPORT ASViewPagerImpl_ViewPagerBean *new_ASViewPagerImpl_ViewPagerBean_initWithASViewPagerImpl_(ASViewPagerImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASViewPagerImpl_ViewPagerBean *create_ASViewPagerImpl_ViewPagerBean_initWithASViewPagerImpl_(ASViewPagerImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASViewPagerImpl_ViewPagerBean)

#endif

#if !defined (ASViewPagerImpl_ViewPagerParamsBean_) && (INCLUDE_ALL_ViewPagerImpl || defined(INCLUDE_ASViewPagerImpl_ViewPagerParamsBean))
#define ASViewPagerImpl_ViewPagerParamsBean_

#define RESTRICT_ViewGroupImpl 1
#define INCLUDE_ASViewGroupImpl_ViewGroupParamsBean 1
#include "ViewGroupImpl.h"

@class ASViewPagerImpl;
@protocol ASIWidget;

@interface ASViewPagerImpl_ViewPagerParamsBean : ASViewGroupImpl_ViewGroupParamsBean

#pragma mark Public

- (instancetype)initWithASViewPagerImpl:(ASViewPagerImpl *)outer$;

- (void)setLayoutGravityWithASIWidget:(id<ASIWidget>)w
                         withNSString:(NSString *)value;

- (void)setLayoutIsdecorWithASIWidget:(id<ASIWidget>)w
                          withBoolean:(jboolean)value;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASViewPagerImpl_ViewPagerParamsBean)

FOUNDATION_EXPORT void ASViewPagerImpl_ViewPagerParamsBean_initWithASViewPagerImpl_(ASViewPagerImpl_ViewPagerParamsBean *self, ASViewPagerImpl *outer$);

FOUNDATION_EXPORT ASViewPagerImpl_ViewPagerParamsBean *new_ASViewPagerImpl_ViewPagerParamsBean_initWithASViewPagerImpl_(ASViewPagerImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASViewPagerImpl_ViewPagerParamsBean *create_ASViewPagerImpl_ViewPagerParamsBean_initWithASViewPagerImpl_(ASViewPagerImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASViewPagerImpl_ViewPagerParamsBean)

#endif

#if !defined (ASViewPagerImpl_ViewPagerCommandParamsBuilder_) && (INCLUDE_ALL_ViewPagerImpl || defined(INCLUDE_ASViewPagerImpl_ViewPagerCommandParamsBuilder))
#define ASViewPagerImpl_ViewPagerCommandParamsBuilder_

#define RESTRICT_ViewGroupImpl 1
#define INCLUDE_ASViewGroupImpl_ViewGroupCommandParamsBuilder 1
#include "ViewGroupImpl.h"

@class ASViewPagerImpl;

@interface ASViewPagerImpl_ViewPagerCommandParamsBuilder : ASViewGroupImpl_ViewGroupCommandParamsBuilder

#pragma mark Public

- (instancetype)initWithASViewPagerImpl:(ASViewPagerImpl *)outer$;

- (ASViewPagerImpl_ViewPagerCommandParamsBuilder *)reset;

- (ASViewPagerImpl_ViewPagerCommandParamsBuilder *)setLayoutGravityWithNSString:(NSString *)value;

- (ASViewPagerImpl_ViewPagerCommandParamsBuilder *)setLayoutIsdecorWithBoolean:(jboolean)value;

- (ASViewPagerImpl_ViewPagerCommandParamsBuilder *)setLayoutMarginBottomWithNSString:(NSString *)arg0;

- (ASViewPagerImpl_ViewPagerCommandParamsBuilder *)setLayoutMarginEndWithNSString:(NSString *)arg0;

- (ASViewPagerImpl_ViewPagerCommandParamsBuilder *)setLayoutMarginHorizontalWithNSString:(NSString *)arg0;

- (ASViewPagerImpl_ViewPagerCommandParamsBuilder *)setLayoutMarginLeftWithNSString:(NSString *)arg0;

- (ASViewPagerImpl_ViewPagerCommandParamsBuilder *)setLayoutMarginRightWithNSString:(NSString *)arg0;

- (ASViewPagerImpl_ViewPagerCommandParamsBuilder *)setLayoutMarginStartWithNSString:(NSString *)arg0;

- (ASViewPagerImpl_ViewPagerCommandParamsBuilder *)setLayoutMarginTopWithNSString:(NSString *)arg0;

- (ASViewPagerImpl_ViewPagerCommandParamsBuilder *)setLayoutMarginVerticalWithNSString:(NSString *)arg0;

- (ASViewPagerImpl_ViewPagerCommandParamsBuilder *)setLayoutMarginWithNSString:(NSString *)arg0;

- (ASViewPagerImpl_ViewPagerCommandParamsBuilder *)tryGetLayoutMarginBottom;

- (ASViewPagerImpl_ViewPagerCommandParamsBuilder *)tryGetLayoutMarginEnd;

- (ASViewPagerImpl_ViewPagerCommandParamsBuilder *)tryGetLayoutMarginLeft;

- (ASViewPagerImpl_ViewPagerCommandParamsBuilder *)tryGetLayoutMarginRight;

- (ASViewPagerImpl_ViewPagerCommandParamsBuilder *)tryGetLayoutMarginStart;

- (ASViewPagerImpl_ViewPagerCommandParamsBuilder *)tryGetLayoutMarginTop;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASViewPagerImpl_ViewPagerCommandParamsBuilder)

FOUNDATION_EXPORT void ASViewPagerImpl_ViewPagerCommandParamsBuilder_initWithASViewPagerImpl_(ASViewPagerImpl_ViewPagerCommandParamsBuilder *self, ASViewPagerImpl *outer$);

FOUNDATION_EXPORT ASViewPagerImpl_ViewPagerCommandParamsBuilder *new_ASViewPagerImpl_ViewPagerCommandParamsBuilder_initWithASViewPagerImpl_(ASViewPagerImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASViewPagerImpl_ViewPagerCommandParamsBuilder *create_ASViewPagerImpl_ViewPagerCommandParamsBuilder_initWithASViewPagerImpl_(ASViewPagerImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASViewPagerImpl_ViewPagerCommandParamsBuilder)

#endif

#pragma pop_macro("INCLUDE_ALL_ViewPagerImpl")
