//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSViewPagerPlugin\src\main\java\com\ashera\viewpager\ViewPagerPlugin.java
//

#include "J2ObjC_source.h"
#include "PagerTabStripImpl.h"
#include "PagerTitleStripImpl.h"
#include "ViewPagerImpl.h"
#include "ViewPagerPlugin.h"
#include "WidgetFactory.h"


@implementation ASViewPagerPlugin

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ASViewPagerPlugin_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (void)initPlugin {
  ASViewPagerPlugin_initPlugin();
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x9, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(initPlugin);
  #pragma clang diagnostic pop
  static const J2ObjcClassInfo _ASViewPagerPlugin = { "ViewPagerPlugin", "com.ashera.viewpager", NULL, methods, NULL, 7, 0x1, 2, 0, -1, -1, -1, -1, -1 };
  return &_ASViewPagerPlugin;
}

@end

void ASViewPagerPlugin_init(ASViewPagerPlugin *self) {
  NSObject_init(self);
}

ASViewPagerPlugin *new_ASViewPagerPlugin_init() {
  J2OBJC_NEW_IMPL(ASViewPagerPlugin, init)
}

ASViewPagerPlugin *create_ASViewPagerPlugin_init() {
  J2OBJC_CREATE_IMPL(ASViewPagerPlugin, init)
}

void ASViewPagerPlugin_initPlugin() {
  ASViewPagerPlugin_initialize();
  ASWidgetFactory_register__WithASIWidget_(new_ASViewPagerImpl_init());
  ASWidgetFactory_register__WithASIWidget_(new_ASPagerTitleStripImpl_init());
  ASWidgetFactory_register__WithASIWidget_(new_ASPagerTabStripImpl_init());
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ASViewPagerPlugin)
